/** Disabled-by-default Robinhood read-only market-data gateway. */
export type RobinhoodHealthStatus = 'connected' | 'unauthorized' | 'rate_limited' | 'timeout' | 'upstream_error' | 'malformed_payload' | 'disabled';
export type RobinhoodReadOnlyOperation = 'get_equity_quotes' | 'get_equity_price_book' | 'get_equity_historicals' | 'get_equity_technical_indicators' | 'get_equity_fundamentals' | 'get_financials' | 'get_earnings_calendar' | 'get_earnings_results' | 'get_index_quotes' | 'get_index_historicals' | 'get_option_quotes' | 'get_option_chains' | 'get_option_historicals' | 'get_option_instruments' | 'search';
export class RobinhoodMarketDataError extends Error { constructor(public readonly status: RobinhoodHealthStatus, message: string, public readonly httpStatus?: number) { super(message); this.name = 'RobinhoodMarketDataError'; } }
type FetchLike = typeof fetch; type Environment = Record<string, string | undefined>; type CacheEntry = { expiresAt: number; value: unknown };
export class RobinhoodMarketDataService {
  private readonly env: Environment; private readonly fetchFn: FetchLike; private readonly now: () => number;
  private readonly cache = new Map<string, CacheEntry>(); private readonly inFlight = new Map<string, Promise<unknown>>();
  private failures = 0; private cooldownUntil = 0; private health: RobinhoodHealthStatus = 'disabled';
  constructor(options: { env?: Environment; fetchFn?: FetchLike; now?: () => number } = {}) { this.env = options.env || process.env; this.fetchFn = options.fetchFn || globalThis.fetch; this.now = options.now || Date.now; if (this.isConfigured()) this.health = 'connected'; }
  isConfigured(): boolean { return this.env.ROBINHOOD_MARKET_DATA_ENABLED === 'true' && this.env.ROBINHOOD_READ_ONLY !== 'false' && Boolean(this.env.ROBINHOOD_MARKET_DATA_BASE_URL?.trim()); }
  getHealth() { return this.cooldownUntil > this.now() ? { status: 'rate_limited' as const, cooldownUntil: this.cooldownUntil } : { status: this.isConfigured() ? this.health : 'disabled' }; }
  async getEquityQuotes(symbols: string[]) { return this.call('get_equity_quotes', { symbols }, this.ttl('quotes')); }
  async getEquityPriceBook(symbols: string[]) { return this.call('get_equity_price_book', { symbols }, this.ttl('book')); }
  async getEquityHistoricals(input: Record<string, unknown>) { return this.call('get_equity_historicals', input, this.ttl('intraday')); }
  async getEquityTechnicalIndicators(input: Record<string, unknown>) { return this.call('get_equity_technical_indicators', input, this.ttl('intraday')); }
  async getEquityFundamentals(symbols: string[]) { return this.call('get_equity_fundamentals', { symbols }, this.ttl('fundamentals')); }
  async getFinancials(input: Record<string, unknown>) { return this.call('get_financials', input, this.ttl('fundamentals')); }
  async getEarningsCalendar(input: Record<string, unknown>) { return this.call('get_earnings_calendar', input, this.ttl('earnings')); }
  async getEarningsResults(symbol: string) { return this.call('get_earnings_results', { symbol }, this.ttl('earnings')); }
  async getIndexQuotes(symbols: string[]) { return this.call('get_index_quotes', { symbols }, this.ttl('quotes')); }
  async getIndexHistoricals(input: Record<string, unknown>) { return this.call('get_index_historicals', input, this.ttl('intraday')); }
  async getOptionQuotes(input: Record<string, unknown>) { return this.call('get_option_quotes', input, this.ttl('quotes')); }
  async getOptionChains(input: Record<string, unknown>) { return this.call('get_option_chains', input, this.ttl('fundamentals')); }
  async getOptionHistoricals(input: Record<string, unknown>) { return this.call('get_option_historicals', input, this.ttl('intraday')); }
  async getOptionInstruments(input: Record<string, unknown>) { return this.call('get_option_instruments', input, this.ttl('fundamentals')); }
  async search(query: string) { return this.call('search', { query }, this.ttl('fundamentals')); }
  private ttl(kind: 'quotes' | 'book' | 'intraday' | 'fundamentals' | 'earnings') { const seconds = kind === 'quotes' ? Number(this.env.ROBINHOOD_CACHE_QUOTES_SECONDS ?? 2) : kind === 'book' ? Number(this.env.ROBINHOOD_CACHE_BOOK_SECONDS ?? 1) : kind === 'intraday' ? Number(this.env.ROBINHOOD_CACHE_INTRADAY_SECONDS ?? 5) : kind === 'earnings' ? 900 : 3600; return Math.max(0, Number.isFinite(seconds) ? seconds * 1000 : 0); }
  private async call(operation: RobinhoodReadOnlyOperation, body: Record<string, unknown>, ttlMs: number): Promise<any> { if (!this.isConfigured()) throw new RobinhoodMarketDataError('disabled', 'Robinhood market data is disabled.'); if (this.cooldownUntil > this.now()) throw new RobinhoodMarketDataError('rate_limited', 'Robinhood market data is in cooldown.'); const key = `${operation}:${JSON.stringify(body)}`; const cached = this.cache.get(key); if (cached && cached.expiresAt > this.now()) return cached.value; const pending = this.inFlight.get(key); if (pending) return pending; const request = this.request(operation, body).then(value => { const gatewayMetadata = value.metadata ?? value.meta ?? value.data?.metadata ?? value.data?.meta ?? {}; const tagged = { ...value, metadata: { ...gatewayMetadata, provider: 'robinhood', sourceType: gatewayMetadata.sourceType ?? 'robinhood_read_only_gateway', liveStatus: gatewayMetadata.liveStatus ?? gatewayMetadata.live_status ?? 'unknown', entitlementStatus: gatewayMetadata.entitlementStatus ?? gatewayMetadata.entitlement_status ?? 'unknown' } }; if (ttlMs > 0) this.cache.set(key, { value: tagged, expiresAt: this.now() + ttlMs }); return tagged; }).finally(() => this.inFlight.delete(key)); this.inFlight.set(key, request); return request; }
  private async request(operation: RobinhoodReadOnlyOperation, body: Record<string, unknown>): Promise<any> { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), Math.max(1, Number(this.env.ROBINHOOD_TIMEOUT_MS ?? 8000))); try { const baseUrl = this.env.ROBINHOOD_MARKET_DATA_BASE_URL!.replace(/\/$/, ''); const token = this.env.ROBINHOOD_MARKET_DATA_PROXY_TOKEN?.trim(); const response = await this.fetchFn(`${baseUrl}/${operation}`, { method: 'POST', signal: controller.signal, headers: { 'content-type': 'application/json', accept: 'application/json', ...(token ? { authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify(body) }); if (!response.ok) { const status: RobinhoodHealthStatus = response.status === 401 || response.status === 403 ? 'unauthorized' : response.status === 429 ? 'rate_limited' : 'upstream_error'; this.fail(status); throw new RobinhoodMarketDataError(status, 'Robinhood market-data gateway rejected the request.', response.status); } let payload: any; try { payload = await response.json(); } catch { this.fail('malformed_payload'); throw new RobinhoodMarketDataError('malformed_payload', 'Robinhood returned invalid JSON.'); } if (!payload || typeof payload !== 'object') { this.fail('malformed_payload'); throw new RobinhoodMarketDataError('malformed_payload', 'Robinhood returned an invalid payload.'); } this.failures = 0; this.cooldownUntil = 0; this.health = 'connected'; return payload; } catch (error) { if (error instanceof RobinhoodMarketDataError) throw error; const status: RobinhoodHealthStatus = controller.signal.aborted ? 'timeout' : 'upstream_error'; this.fail(status); throw new RobinhoodMarketDataError(status, 'Robinhood market-data request failed.'); } finally { clearTimeout(timer); } }
  private fail(status: RobinhoodHealthStatus): void { this.health = status; if (status === 'rate_limited') { this.failures += 1; this.cooldownUntil = this.now() + Math.min(60_000, 1_000 * 2 ** Math.min(this.failures, 6)); } }
}
