import assert from 'node:assert/strict';
import test from 'node:test';
import { computeConsensus, parseProviderOpinion } from '../src/server/ai/consensusEngine';
import { ProviderStateRegistry } from '../src/server/ai/providerState';
import { OpenAIProvider } from '../src/server/ai/providers/openaiProvider';
import { GeminiProvider } from '../src/server/ai/providers/geminiProvider';
import { AnthropicProvider } from '../src/server/ai/providers/anthropicProvider';
import { PerplexityProvider } from '../src/server/ai/providers/perplexityProvider';
import { MarketMindNewsEngine } from '../src/services/MarketMindNewsEngine';
import { buildMarketOutcome } from '../src/services/ai/marketOutcomeEngine';
import { ReputablePublisherProvider, reputablePublisherConfigs } from '../src/services/newsProviders/ReputablePublisherProvider';
import type { NewsArticle } from '../src/types/newsIntelligence';
import type { ProviderOpinion } from '../src/server/ai/types';

const article = (overrides: Partial<NewsArticle> = {}): NewsArticle => ({ id: 'a', headline: 'Company raises guidance after earnings', summary: 'Guidance increased.', url: 'https://example.com/a', source: 'Example', providerId: 'example', sourceTier: 'TIER_2_FINANCIAL', sourceType: 'LICENSED_API', tickers: ['XYZ'], category: 'EARNINGS', region: 'US', publishedAt: new Date().toISOString(), retrievedAt: new Date().toISOString(), sentiment: 'BULLISH', impact: 'HIGH', impactScore: 75, verificationStatus: 'DEVELOPING', affectedAssets: ['XYZ'], ...overrides });
const opinion = (provider: ProviderOpinion['provider'], direction: ProviderOpinion['direction'], confidence = 80): ProviderOpinion => ({ provider, direction, confidence, catalysts: ['guidance'], risks: ['execution'], invalidationConditions: ['guidance withdrawn'], affectedAssets: ['XYZ'], timeHorizon: '1_3_DAYS', citations: ['https://example.com/a'] });

test('all four server providers fail closed when unconfigured', () => { for (const provider of [new OpenAIProvider(), new GeminiProvider(), new AnthropicProvider(), new PerplexityProvider()]) assert.equal(provider.isAvailable(), false); });
test('provider opinion parser rejects fabricated unstructured fallback text', () => assert.throws(() => parseProviderOpinion('openai', 'probably bullish')));
test('consensus measures agreement and disagreement without treating models as sources', () => { const result = computeConsensus([opinion('openai', 'BULLISH'), opinion('gemini', 'BULLISH'), opinion('anthropic', 'BEARISH')], ['perplexity'], 1); assert.equal(result.providerAgreementScore, 67); assert.equal(result.disagreementScore, 33); assert.equal(result.evidenceStrength, 'WEAK'); assert.equal(result.providersUnavailable[0], 'perplexity'); });
test('circuit breaker opens after bounded consecutive failures and resets', () => { const state = new ProviderStateRegistry(2, 10); state.failure('openai'); assert.equal(state.isCircuitOpen('openai'), false); state.failure('openai'); assert.equal(state.isCircuitOpen('openai'), true); assert.equal(state.isCircuitOpen('openai', Date.now() + 20), false); });
test('syndicated duplicate coverage counts once', () => { const items = [article({ id: 'a', providerId: 'wire_a', sourceMetadata: { publisher: 'A', providerId: 'wire_a', sourceTier: 'TIER_2_FINANCIAL', sourceType: 'LICENSED_API', canonicalUrl: 'https://a.test/story', publishedAt: new Date().toISOString(), retrievedAt: new Date().toISOString(), syndicationId: 'wire-1' } }), article({ id: 'b', providerId: 'wire_b', url: 'https://b.test/story', sourceMetadata: { publisher: 'B', providerId: 'wire_b', sourceTier: 'TIER_2_FINANCIAL', sourceType: 'LICENSED_API', canonicalUrl: 'https://b.test/story', publishedAt: new Date().toISOString(), retrievedAt: new Date().toISOString(), syndicationId: 'wire-1' } })]; assert.equal(MarketMindNewsEngine.independentSources(items).length, 1); assert.equal(MarketMindNewsEngine.evaluateVerificationStatus(items), 'DEVELOPING'); });
test('two independent reputable reports confirm while opposing reports conflict', () => { const second = article({ id: 'b', providerId: 'other', url: 'https://other.test/b' }); assert.equal(MarketMindNewsEngine.evaluateVerificationStatus([article(), second]), 'CONFIRMED'); assert.equal(MarketMindNewsEngine.evaluateVerificationStatus([article(), second, article({ id: 'c', providerId: 'third', url: 'https://third.test/c', sentiment: 'BEARISH' })]), 'CONFLICTED'); });
test('official primary source confirms directly and stale evidence is marked stale', () => { assert.equal(MarketMindNewsEngine.evaluateVerificationStatus([article({ sourceTier: 'TIER_1_PRIMARY' })]), 'CONFIRMED'); assert.equal(MarketMindNewsEngine.evaluateVerificationStatus([article({ publishedAt: new Date(Date.now() - 80 * 60 * 60 * 1000).toISOString() })]), 'STALE'); });
test('missing URL or timestamp remains unverified and is never attributed as evidence', () => { const invalid = article({ url: '', publishedAt: '' }); assert.equal(MarketMindNewsEngine.evaluateVerificationStatus([invalid]), 'UNVERIFIED'); assert.throws(() => buildMarketOutcome({ ticker: 'XYZ', articles: [], consensus: computeConsensus([opinion('openai', 'BULLISH'), opinion('gemini', 'BULLISH')], [], 0) })); });
test('Market Outcome probabilities total exactly 100 and exposes unavailable market data', () => { const items = [article(), article({ id: 'b', providerId: 'other', url: 'https://other.test/b' })]; const outcome = buildMarketOutcome({ ticker: 'XYZ', articles: items, consensus: computeConsensus([opinion('openai', 'BULLISH'), opinion('gemini', 'BULLISH')], [], 2) }); assert.equal(outcome.bullishProbability + outcome.neutralProbability + outcome.bearishProbability, 100); assert.equal(outcome.marketConfirmation?.priceMove, null); assert.match(outcome.disclaimer, /probabilistic/i); assert.equal(outcome.evidence.length, 2); });
test('Market Outcome confidence degrades for one source, disagreement, stale evidence, and unavailable market data', () => { const strong = buildMarketOutcome({ articles: [article(), article({ id: 'b', providerId: 'other', url: 'https://other.test/b' })], consensus: computeConsensus([opinion('openai', 'BULLISH'), opinion('gemini', 'BULLISH')], [], 2), marketReaction: { verified: true } }); const weak = buildMarketOutcome({ articles: [article()], consensus: computeConsensus([opinion('openai', 'BULLISH'), opinion('gemini', 'BEARISH')], [], 1) }); assert.ok(weak.confidence < strong.confidence); assert.equal(weak.aiConsensus.uncertaintyFlag, true); });
test('licensed publisher boundaries are code-ready but unconfigured and return no fabricated news', async () => { for (const config of reputablePublisherConfigs) { const provider = new ReputablePublisherProvider(config, {}); assert.equal((await provider.getHealth()).status, 'NOT_CONFIGURED'); assert.deepEqual(await provider.getLatestNews(), []); } });
