import {
  BrokerId,
  ConnectedBrokerAccount,
  HoldingPosition,
  OptionsPosition,
  PortfolioTransaction,
  BrokerProviderMetadata,
} from '../../types/portfolio.js';
import { BrokerProvider, BrokerAuthCredentials, ConnectAccountResult } from './BrokerProvider.js';

export class DemoInstitutionalBrokerProvider extends BrokerProvider {
  readonly brokerId: BrokerId = 'demo';
  readonly metadata: BrokerProviderMetadata = {
    id: 'demo',
    name: 'MarketMind Demo Institutional Account',
    logo: '🏛️',
    description: 'Instant institutional-grade demonstration portfolio with 10 holdings, active options, and transaction history.',
    authType: 'oauth',
    supportedAccountTypes: ['individual_taxable', 'margin', 'roth_ira'],
    supportsOptions: true,
    supportsRealtimeQuotes: true,
    supportsHistoricalTransactions: true,
    connectionInstructions: 'Instantly connects a verified sample portfolio to test all MarketMind Connected Portfolio™ features.',
    isAvailable: true,
  };

  private static sampleHoldings: HoldingPosition[] = [
    {
      id: 'pos-nvda',
      accountId: 'demo-acc-01',
      symbol: 'NVDA',
      companyName: 'NVIDIA Corporation',
      assetClass: 'EQUITY',
      quantity: 130,
      averageCost: 118.50,
      currentPrice: 132.80,
      marketValue: 17264.00,
      costBasis: 15405.00,
      dailyChangeDollar: -3.45,
      dailyChangePercent: -2.53,
      unrealizedGainDollar: 1859.00,
      unrealizedGainPercent: 12.07,
      realizedGainDollar: 420.00,
      portfolioWeight: 0.208,
      marketMindScore: 84,
      riskRating: 'HIGH',
      sector: 'Technology',
      industry: 'Semiconductors',
      beta: 1.85,
      dividendYield: 0.03,
      nextEarningsDate: '2026-08-26',
      dayHigh: 136.20,
      dayLow: 131.50,
      volume: 48200000,
    },
    {
      id: 'pos-aapl',
      accountId: 'demo-acc-01',
      symbol: 'AAPL',
      companyName: 'Apple Inc.',
      assetClass: 'EQUITY',
      quantity: 65,
      averageCost: 215.20,
      currentPrice: 228.40,
      marketValue: 14846.00,
      costBasis: 13988.00,
      dailyChangeDollar: 1.15,
      dailyChangePercent: 0.51,
      unrealizedGainDollar: 858.00,
      unrealizedGainPercent: 6.13,
      realizedGainDollar: 150.00,
      portfolioWeight: 0.179,
      marketMindScore: 76,
      riskRating: 'MEDIUM',
      sector: 'Technology',
      industry: 'Consumer Electronics',
      beta: 1.05,
      dividendYield: 0.44,
      nextEarningsDate: '2026-10-29',
      dayHigh: 229.80,
      dayLow: 226.50,
      volume: 32000000,
    },
    {
      id: 'pos-msft',
      accountId: 'demo-acc-01',
      symbol: 'MSFT',
      companyName: 'Microsoft Corporation',
      assetClass: 'EQUITY',
      quantity: 28,
      averageCost: 412.00,
      currentPrice: 424.50,
      marketValue: 11886.00,
      costBasis: 11536.00,
      dailyChangeDollar: -2.10,
      dailyChangePercent: -0.49,
      unrealizedGainDollar: 350.00,
      unrealizedGainPercent: 3.03,
      realizedGainDollar: 0,
      portfolioWeight: 0.143,
      marketMindScore: 79,
      riskRating: 'MEDIUM',
      sector: 'Technology',
      industry: 'Software - Infrastructure',
      beta: 1.12,
      dividendYield: 0.72,
      nextEarningsDate: '2026-10-22',
      dayHigh: 428.10,
      dayLow: 423.00,
      volume: 18500000,
    },
    {
      id: 'pos-amd',
      accountId: 'demo-acc-01',
      symbol: 'AMD',
      companyName: 'Advanced Micro Devices, Inc.',
      assetClass: 'EQUITY',
      quantity: 55,
      averageCost: 148.00,
      currentPrice: 156.40,
      marketValue: 8602.00,
      costBasis: 8140.00,
      dailyChangeDollar: -4.20,
      dailyChangePercent: -2.61,
      unrealizedGainDollar: 462.00,
      unrealizedGainPercent: 5.68,
      realizedGainDollar: 0,
      portfolioWeight: 0.104,
      marketMindScore: 71,
      riskRating: 'HIGH',
      sector: 'Technology',
      industry: 'Semiconductors',
      beta: 1.92,
      dividendYield: 0.0,
      nextEarningsDate: '2026-10-27',
      dayHigh: 161.40,
      dayLow: 155.00,
      volume: 24000000,
    },
    {
      id: 'pos-amzn',
      accountId: 'demo-acc-01',
      symbol: 'AMZN',
      companyName: 'Amazon.com, Inc.',
      assetClass: 'EQUITY',
      quantity: 40,
      averageCost: 178.50,
      currentPrice: 188.60,
      marketValue: 7544.00,
      costBasis: 7140.00,
      dailyChangeDollar: 0.85,
      dailyChangePercent: 0.45,
      unrealizedGainDollar: 404.00,
      unrealizedGainPercent: 5.66,
      realizedGainDollar: 0,
      portfolioWeight: 0.091,
      marketMindScore: 81,
      riskRating: 'MEDIUM',
      sector: 'Consumer Cyclical',
      industry: 'Internet Retail',
      beta: 1.28,
      dividendYield: 0.0,
      nextEarningsDate: '2026-10-29',
      dayHigh: 190.20,
      dayLow: 186.80,
      volume: 22000000,
    },
    {
      id: 'pos-spy',
      accountId: 'demo-acc-01',
      symbol: 'SPY',
      companyName: 'SPDR S&P 500 ETF Trust',
      assetClass: 'ETF',
      quantity: 14,
      averageCost: 535.00,
      currentPrice: 554.20,
      marketValue: 7758.80,
      costBasis: 7490.00,
      dailyChangeDollar: -1.80,
      dailyChangePercent: -0.32,
      unrealizedGainDollar: 268.80,
      unrealizedGainPercent: 3.59,
      realizedGainDollar: 0,
      portfolioWeight: 0.093,
      marketMindScore: 68,
      riskRating: 'LOW',
      sector: 'Diversified Index',
      industry: 'Large Cap Blend',
      beta: 1.00,
      dividendYield: 1.25,
      nextEarningsDate: undefined,
      dayHigh: 557.00,
      dayLow: 553.20,
      volume: 42000000,
    },
    {
      id: 'pos-jpm',
      accountId: 'demo-acc-01',
      symbol: 'JPM',
      companyName: 'JPMorgan Chase & Co.',
      assetClass: 'EQUITY',
      quantity: 25,
      averageCost: 205.00,
      currentPrice: 222.80,
      marketValue: 5570.00,
      costBasis: 5125.00,
      dailyChangeDollar: 1.40,
      dailyChangePercent: 0.63,
      unrealizedGainDollar: 445.00,
      unrealizedGainPercent: 8.68,
      realizedGainDollar: 120.00,
      portfolioWeight: 0.067,
      marketMindScore: 78,
      riskRating: 'LOW',
      sector: 'Financial Services',
      industry: 'Banks - Diversified',
      beta: 0.88,
      dividendYield: 2.15,
      nextEarningsDate: '2026-10-14',
      dayHigh: 224.50,
      dayLow: 221.00,
      volume: 8500000,
    },
    {
      id: 'pos-lly',
      accountId: 'demo-acc-01',
      symbol: 'LLY',
      companyName: 'Eli Lilly and Company',
      assetClass: 'EQUITY',
      quantity: 5,
      averageCost: 880.00,
      currentPrice: 945.00,
      marketValue: 4725.00,
      costBasis: 4400.00,
      dailyChangeDollar: 4.50,
      dailyChangePercent: 0.48,
      unrealizedGainDollar: 325.00,
      unrealizedGainPercent: 7.39,
      realizedGainDollar: 0,
      portfolioWeight: 0.057,
      marketMindScore: 86,
      riskRating: 'MEDIUM',
      sector: 'Healthcare',
      industry: 'Drug Manufacturers',
      beta: 0.65,
      dividendYield: 0.55,
      nextEarningsDate: '2026-10-30',
      dayHigh: 952.00,
      dayLow: 938.00,
      volume: 2800000,
    },
  ];

  private static sampleOptions: OptionsPosition[] = [
    {
      id: 'opt-nvda-call',
      accountId: 'demo-acc-01',
      symbol: 'NVDA 260918C00140000',
      underlyingSymbol: 'NVDA',
      contractType: 'CALL',
      strikePrice: 140.00,
      expirationDate: '2026-09-18',
      daysToExpiration: 34,
      quantity: 2,
      currentPrice: 5.80,
      costBasis: 4.20,
      marketValue: 1160.00,
      unrealizedGainDollar: 320.00,
      unrealizedGainPercent: 38.10,
      delta: 0.44,
      gamma: 0.038,
      theta: -0.12,
      vega: 0.18,
      impliedVolatility: 0.46,
      inTheMoney: false,
      riskFlags: ['EARNINGS_BEFORE_EXP'],
    },
    {
      id: 'opt-spy-hedge-put',
      accountId: 'demo-acc-01',
      symbol: 'SPY 260828P00540000',
      underlyingSymbol: 'SPY',
      contractType: 'PUT',
      strikePrice: 540.00,
      expirationDate: '2026-08-28',
      daysToExpiration: 13,
      quantity: 1,
      currentPrice: 2.15,
      costBasis: 2.80,
      marketValue: 215.00,
      unrealizedGainDollar: -65.00,
      unrealizedGainPercent: -23.21,
      delta: -0.22,
      gamma: 0.024,
      theta: -0.18,
      vega: 0.11,
      impliedVolatility: 0.15,
      inTheMoney: false,
      riskFlags: ['SHORT_EXPIRATION', 'HIGH_THETA'],
    },
  ];

  private static sampleTransactions: PortfolioTransaction[] = [
    {
      id: 'tx-001',
      accountId: 'demo-acc-01',
      date: '2026-08-12',
      type: 'BUY',
      symbol: 'NVDA',
      description: 'Bought 30 shares NVDA @ $128.50',
      quantity: 30,
      price: 128.50,
      amount: -3855.00,
      fees: 0,
    },
    {
      id: 'tx-002',
      accountId: 'demo-acc-01',
      date: '2026-08-08',
      type: 'DIVIDEND',
      symbol: 'JPM',
      description: 'Dividend payment JPM ($1.15/share)',
      quantity: 25,
      price: 1.15,
      amount: 28.75,
      fees: 0,
    },
    {
      id: 'tx-003',
      accountId: 'demo-acc-01',
      date: '2026-08-01',
      type: 'OPTION_BUY',
      symbol: 'NVDA 260918C00140000',
      description: 'Bought 2 Contracts NVDA Sep 18 $140 Call @ $4.20',
      quantity: 2,
      price: 4.20,
      amount: -840.00,
      fees: 1.30,
    },
    {
      id: 'tx-004',
      accountId: 'demo-acc-01',
      date: '2026-07-25',
      type: 'SELL',
      symbol: 'AAPL',
      description: 'Sold 10 shares AAPL @ $224.00',
      quantity: 10,
      price: 224.00,
      amount: 2240.00,
      fees: 0.05,
    },
    {
      id: 'tx-005',
      accountId: 'demo-acc-01',
      date: '2026-07-15',
      type: 'DEPOSIT',
      description: 'Electronic ACH Transfer from Checking',
      amount: 5000.00,
      fees: 0,
    },
  ];

  async connectAccount(userId: string, credentials: BrokerAuthCredentials): Promise<ConnectAccountResult> {
    const now = new Date();
    const account: ConnectedBrokerAccount = {
      id: 'demo-acc-01',
      userId,
      brokerId: 'demo',
      brokerName: 'MarketMind Demo Prime Brokerage',
      accountNickname: 'Main Institutional Growth Account',
      accountNumberMasked: '****-9482',
      accountType: 'individual_taxable',
      status: 'CONNECTED',
      lastSyncedAt: now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', second: '2-digit' }) + ' ET',
      cashBalance: 5800.00,
      buyingPower: 11600.00,
      portfolioValue: 84420.80,
      totalCostBasis: 76174.00,
      dayChangeDollar: -1553.34,
      dayChangePercent: -1.84,
      totalGainDollar: 8246.80,
      totalGainPercent: 10.83,
      holdingsCount: DemoInstitutionalBrokerProvider.sampleHoldings.length,
      optionsCount: DemoInstitutionalBrokerProvider.sampleOptions.length,
      isReadOnly: true,
      authExpiresAt: new Date(now.getTime() + 90 * 86400000).toISOString(),
      connectionMetadata: {
        institutionLogo: '🏛️',
        environment: 'live',
        permissions: ['READ_BALANCES', 'READ_POSITIONS', 'READ_TRANSACTIONS', 'READ_OPTIONS'],
      },
    };

    return {
      success: true,
      account,
      accounts: [account],
    };
  }

  async disconnectAccount(accountId: string): Promise<boolean> {
    return true;
  }

  async refreshConnection(accountId: string): Promise<{ success: boolean; status: string }> {
    return { success: true, status: 'CONNECTED' };
  }

  async getAccounts(accountId: string): Promise<ConnectedBrokerAccount[]> {
    const res = await this.connectAccount('user_current', {});
    return res.accounts || [];
  }

  async getBalances(accountId: string): Promise<{
    cashBalance: number;
    buyingPower: number;
    portfolioValue: number;
    totalCostBasis: number;
  }> {
    return {
      cashBalance: 5800.00,
      buyingPower: 11600.00,
      portfolioValue: 84420.80,
      totalCostBasis: 76174.00,
    };
  }

  async getPositions(accountId: string): Promise<HoldingPosition[]> {
    return DemoInstitutionalBrokerProvider.sampleHoldings;
  }

  async getOptionsPositions(accountId: string): Promise<OptionsPosition[]> {
    return DemoInstitutionalBrokerProvider.sampleOptions;
  }

  async getTransactions(accountId: string, limit?: number): Promise<PortfolioTransaction[]> {
    return DemoInstitutionalBrokerProvider.sampleTransactions.slice(0, limit || 50);
  }

  async getAccountMetadata(accountId: string): Promise<Record<string, any>> {
    return {
      institution: 'MarketMind Demo Prime Brokerage',
      accountNumber: '****-9482',
      readOnly: true,
      isPaper: false,
      clearingHouse: 'Apex Clearing / DTCC',
      sipProtection: '$500,000 SIPC Insured',
    };
  }
}
