import {
  NormalizedInstrument,
  UniversalAssetClass,
  InstrumentSearchResultGroup,
  ProviderSymbolMap,
} from '../../types/instrument.js';
import { ADDITIONAL_INSTRUMENTS } from './additionalInstrumentCatalog.js';

// ==========================================
// Base Universal Multi-Asset Reference List
// ==========================================
const BASE_MASTER_INSTRUMENTS: NormalizedInstrument[] = [
  // --- 1. U.S. & INTERNATIONAL STOCKS ---
  {
    instrumentId: 'inst_stock_nvda_nasdaq',
    symbol: 'NVDA',
    displaySymbol: 'NVDA',
    name: 'NVIDIA Corporation',
    assetClass: 'STOCK',
    instrumentType: 'Common Stock',
    exchange: 'NASDAQ',
    exchangeMIC: 'XNAS',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'NVDA',
    providerSymbols: {
      massive: 'NVDA',
      finnhub: 'NVDA',
      alpaca: 'NVDA',
      benzinga: 'NVDA',
      yahoo: 'NVDA',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_EXTENDED',
    isin: 'US67066G1040',
    figi: 'BBG000BBJQV0',
    cusip: '67066G104',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 129.60,
    change: 3.45,
    changePercent: 2.74,
    bid: 129.58,
    ask: 129.62,
    spread: 0.04,
    volume: 62450000,
    high: 130.40,
    low: 126.80,
    open: 127.10,
    previousClose: 126.15,
    fiftyTwoWeekHigh: 140.76,
    fiftyTwoWeekLow: 45.11,
    marketCap: 3180000000000,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_stock_aapl_nasdaq',
    symbol: 'AAPL',
    displaySymbol: 'AAPL',
    name: 'Apple Inc.',
    assetClass: 'STOCK',
    instrumentType: 'Common Stock',
    exchange: 'NASDAQ',
    exchangeMIC: 'XNAS',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'AAPL',
    providerSymbols: {
      massive: 'AAPL',
      finnhub: 'AAPL',
      alpaca: 'AAPL',
      benzinga: 'AAPL',
      yahoo: 'AAPL',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_EXTENDED',
    isin: 'US0378331005',
    figi: 'BBG000B9XRY4',
    cusip: '037833100',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 224.75,
    change: 0.85,
    changePercent: 0.38,
    bid: 224.72,
    ask: 224.78,
    spread: 0.06,
    volume: 38200000,
    high: 225.40,
    low: 223.50,
    open: 224.10,
    previousClose: 223.90,
    fiftyTwoWeekHigh: 237.23,
    fiftyTwoWeekLow: 164.08,
    marketCap: 3420000000000,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_stock_tsla_nasdaq',
    symbol: 'TSLA',
    displaySymbol: 'TSLA',
    name: 'Tesla, Inc.',
    assetClass: 'STOCK',
    instrumentType: 'Common Stock',
    exchange: 'NASDAQ',
    exchangeMIC: 'XNAS',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'TSLA',
    providerSymbols: {
      massive: 'TSLA',
      finnhub: 'TSLA',
      alpaca: 'TSLA',
      benzinga: 'TSLA',
      yahoo: 'TSLA',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_EXTENDED',
    isin: 'US88160R1014',
    figi: 'BBG000N9MNX3',
    cusip: '88160R101',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 216.20,
    change: -2.80,
    changePercent: -1.28,
    bid: 216.15,
    ask: 216.25,
    spread: 0.10,
    volume: 48900000,
    high: 221.40,
    low: 214.60,
    open: 220.00,
    previousClose: 219.00,
    fiftyTwoWeekHigh: 271.00,
    fiftyTwoWeekLow: 138.80,
    marketCap: 688000000000,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_stock_msft_nasdaq',
    symbol: 'MSFT',
    displaySymbol: 'MSFT',
    name: 'Microsoft Corporation',
    assetClass: 'STOCK',
    instrumentType: 'Common Stock',
    exchange: 'NASDAQ',
    exchangeMIC: 'XNAS',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'MSFT',
    providerSymbols: {
      massive: 'MSFT',
      finnhub: 'MSFT',
      alpaca: 'MSFT',
      benzinga: 'MSFT',
      yahoo: 'MSFT',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_EXTENDED',
    isin: 'US5949181045',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 426.50,
    change: 3.20,
    changePercent: 0.76,
    volume: 18400000,
    previousClose: 423.30,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_stock_amzn_nasdaq',
    symbol: 'AMZN',
    displaySymbol: 'AMZN',
    name: 'Amazon.com, Inc.',
    assetClass: 'STOCK',
    instrumentType: 'Common Stock',
    exchange: 'NASDAQ',
    exchangeMIC: 'XNAS',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'AMZN',
    providerSymbols: {
      massive: 'AMZN',
      finnhub: 'AMZN',
      alpaca: 'AMZN',
      benzinga: 'AMZN',
      yahoo: 'AMZN',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_EXTENDED',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 182.30,
    change: 1.60,
    changePercent: 0.89,
    volume: 22000000,
    previousClose: 180.70,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_stock_meta_nasdaq',
    symbol: 'META',
    displaySymbol: 'META',
    name: 'Meta Platforms, Inc.',
    assetClass: 'STOCK',
    instrumentType: 'Common Stock',
    exchange: 'NASDAQ',
    exchangeMIC: 'XNAS',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'META',
    providerSymbols: {
      massive: 'META',
      finnhub: 'META',
      alpaca: 'META',
      benzinga: 'META',
      yahoo: 'META',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_EXTENDED',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 504.10,
    change: 6.80,
    changePercent: 1.37,
    volume: 14500000,
    previousClose: 497.30,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_stock_amd_nasdaq',
    symbol: 'AMD',
    displaySymbol: 'AMD',
    name: 'Advanced Micro Devices, Inc.',
    assetClass: 'STOCK',
    instrumentType: 'Common Stock',
    exchange: 'NASDAQ',
    exchangeMIC: 'XNAS',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'AMD',
    providerSymbols: {
      massive: 'AMD',
      finnhub: 'AMD',
      alpaca: 'AMD',
      benzinga: 'AMD',
      yahoo: 'AMD',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_EXTENDED',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 148.90,
    change: 2.90,
    changePercent: 1.99,
    volume: 31200000,
    previousClose: 146.00,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_stock_coin_nasdaq',
    symbol: 'COIN',
    displaySymbol: 'COIN',
    name: 'Coinbase Global, Inc.',
    assetClass: 'STOCK',
    instrumentType: 'Common Stock',
    exchange: 'NASDAQ',
    exchangeMIC: 'XNAS',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'COIN',
    providerSymbols: {
      massive: 'COIN',
      finnhub: 'COIN',
      alpaca: 'COIN',
      benzinga: 'COIN',
      yahoo: 'COIN',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_EXTENDED',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 218.40,
    change: 8.50,
    changePercent: 4.05,
    volume: 12100000,
    previousClose: 209.90,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_stock_pltr_nyse',
    symbol: 'PLTR',
    displaySymbol: 'PLTR',
    name: 'Palantir Technologies Inc.',
    assetClass: 'STOCK',
    instrumentType: 'Common Stock',
    exchange: 'NYSE',
    exchangeMIC: 'XNYS',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'PLTR',
    providerSymbols: {
      massive: 'PLTR',
      finnhub: 'PLTR',
      alpaca: 'PLTR',
      benzinga: 'PLTR',
      yahoo: 'PLTR',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_EXTENDED',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 31.80,
    change: 0.95,
    changePercent: 3.08,
    volume: 54000000,
    previousClose: 30.85,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_adr_tsm_nyse',
    symbol: 'TSM',
    displaySymbol: 'TSM',
    name: 'Taiwan Semiconductor Manufacturing Co. (ADR)',
    assetClass: 'ADR',
    instrumentType: 'American Depositary Receipt',
    exchange: 'NYSE',
    exchangeMIC: 'XNYS',
    country: 'Taiwan',
    currency: 'USD',
    providerSymbol: 'TSM',
    providerSymbols: {
      massive: 'TSM',
      finnhub: 'TSM',
      alpaca: 'TSM',
      yahoo: 'TSM',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_EXTENDED',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 172.50,
    change: 3.80,
    changePercent: 2.25,
    volume: 16500000,
    previousClose: 168.70,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_adr_asml_nasdaq',
    symbol: 'ASML',
    displaySymbol: 'ASML',
    name: 'ASML Holding N.V. (ADR)',
    assetClass: 'ADR',
    instrumentType: 'American Depositary Receipt',
    exchange: 'NASDAQ',
    exchangeMIC: 'XNAS',
    country: 'Netherlands',
    currency: 'USD',
    providerSymbol: 'ASML',
    providerSymbols: {
      massive: 'ASML',
      finnhub: 'ASML',
      alpaca: 'ASML',
      yahoo: 'ASML',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_EXTENDED',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 885.40,
    change: 14.20,
    changePercent: 1.63,
    volume: 1200000,
    previousClose: 871.20,
    lastUpdated: new Date().toISOString(),
  },

  {
    instrumentId: 'inst_stock_ibm_nyse',
    symbol: 'IBM',
    displaySymbol: 'IBM',
    name: 'International Business Machines Corp.',
    assetClass: 'STOCK',
    instrumentType: 'Common Stock',
    exchange: 'NYSE',
    exchangeMIC: 'XNYS',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'IBM',
    providerSymbols: {
      massive: 'IBM',
      finnhub: 'IBM',
      alpaca: 'IBM',
      benzinga: 'IBM',
      yahoo: 'IBM',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_EXTENDED',
    isin: 'US4592001014',
    figi: 'BBG000BLNNH6',
    cusip: '459200101',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 194.25,
    change: 1.85,
    changePercent: 0.96,
    bid: 194.20,
    ask: 194.30,
    spread: 0.10,
    volume: 3850000,
    high: 195.40,
    low: 192.80,
    open: 193.10,
    previousClose: 192.40,
    fiftyTwoWeekHigh: 200.55,
    fiftyTwoWeekLow: 137.40,
    marketCap: 178000000000,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_stock_brkb_nyse',
    symbol: 'BRK.B',
    displaySymbol: 'BRK.B',
    name: 'Berkshire Hathaway Inc. Class B',
    assetClass: 'STOCK',
    instrumentType: 'Common Stock',
    exchange: 'NYSE',
    exchangeMIC: 'XNYS',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'BRK.B',
    providerSymbols: {
      massive: 'BRK.B',
      finnhub: 'BRK.B',
      alpaca: 'BRK.B',
      benzinga: 'BRK.B',
      yahoo: 'BRK-B',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_EXTENDED',
    isin: 'US0846707026',
    figi: 'BBG000B9Y5X2',
    cusip: '084670702',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 452.80,
    change: 3.20,
    changePercent: 0.71,
    bid: 452.75,
    ask: 452.85,
    spread: 0.10,
    volume: 3120000,
    high: 454.20,
    low: 450.10,
    open: 450.90,
    previousClose: 449.60,
    fiftyTwoWeekHigh: 460.00,
    fiftyTwoWeekLow: 345.50,
    marketCap: 980000000000,
    lastUpdated: new Date().toISOString(),
  },

  // --- 2. ETFS & MUTUAL FUNDS ---
  {
    instrumentId: 'inst_etf_spy_nyse',
    symbol: 'SPY',
    displaySymbol: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    assetClass: 'ETF',
    instrumentType: 'Exchange-Traded Fund',
    exchange: 'NYSE Arca',
    exchangeMIC: 'ARCX',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'SPY',
    providerSymbols: {
      massive: 'SPY',
      finnhub: 'SPY',
      alpaca: 'SPY',
      benzinga: 'SPY',
      yahoo: 'SPY',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_EXTENDED',
    isin: 'US78462F1030',
    cusip: '78462F103',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 512.48,
    change: 4.20,
    changePercent: 0.83,
    bid: 512.45,
    ask: 512.50,
    spread: 0.05,
    volume: 64250000,
    high: 513.80,
    low: 509.10,
    open: 510.20,
    previousClose: 508.28,
    fiftyTwoWeekHigh: 565.16,
    fiftyTwoWeekLow: 410.08,
    marketCap: 560000000000,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_etf_qqq_nasdaq',
    symbol: 'QQQ',
    displaySymbol: 'QQQ',
    name: 'Invesco QQQ Trust (Nasdaq-100)',
    assetClass: 'ETF',
    instrumentType: 'Exchange-Traded Fund',
    exchange: 'NASDAQ',
    exchangeMIC: 'XNAS',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'QQQ',
    providerSymbols: {
      massive: 'QQQ',
      finnhub: 'QQQ',
      alpaca: 'QQQ',
      benzinga: 'QQQ',
      yahoo: 'QQQ',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_EXTENDED',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 442.35,
    change: 5.05,
    changePercent: 1.15,
    volume: 38400000,
    previousClose: 437.30,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_etf_iwm_nyse',
    symbol: 'IWM',
    displaySymbol: 'IWM',
    name: 'iShares Russell 2000 ETF',
    assetClass: 'ETF',
    instrumentType: 'Exchange-Traded Fund',
    exchange: 'NYSE Arca',
    exchangeMIC: 'ARCX',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'IWM',
    providerSymbols: {
      massive: 'IWM',
      finnhub: 'IWM',
      alpaca: 'IWM',
      yahoo: 'IWM',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_EXTENDED',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 214.80,
    change: 1.38,
    changePercent: 0.65,
    volume: 19800000,
    previousClose: 213.42,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_etf_tlt_nasdaq',
    symbol: 'TLT',
    displaySymbol: 'TLT',
    name: 'iShares 20+ Year Treasury Bond ETF',
    assetClass: 'ETF',
    instrumentType: 'Bond ETF',
    exchange: 'NASDAQ',
    exchangeMIC: 'XNAS',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'TLT',
    providerSymbols: {
      massive: 'TLT',
      finnhub: 'TLT',
      alpaca: 'TLT',
      yahoo: 'TLT',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_EXTENDED',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 94.60,
    change: 0.72,
    changePercent: 0.77,
    volume: 24500000,
    previousClose: 93.88,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_fund_vfiax',
    symbol: 'VFIAX',
    displaySymbol: 'VFIAX',
    name: 'Vanguard 500 Index Fund Admiral Shares',
    assetClass: 'FUND',
    instrumentType: 'Mutual Fund',
    exchange: 'NASDAQ Fund Network',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'VFIAX',
    providerSymbols: {
      yahoo: 'VFIAX',
      finnhub: 'VFIAX',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_REGULAR',
    activeStatus: 'ACTIVE',
    primaryProvider: 'yahoo',
    realTimeStatus: 'END_OF_DAY',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 498.32,
    change: 3.84,
    changePercent: 0.78,
    previousClose: 494.48,
    lastUpdated: new Date().toISOString(),
  },

  // --- 3. STOCK INDEXES & BENCHMARKS ---
  {
    instrumentId: 'inst_index_spx_cboe',
    symbol: 'SPX',
    displaySymbol: 'SPX',
    name: 'S&P 500 Benchmark Index',
    assetClass: 'INDEX',
    instrumentType: 'Cash Index',
    exchange: 'CBOE',
    exchangeMIC: 'XCBO',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'I:SPX',
    providerSymbols: {
      massive: 'I:SPX',
      yahoo: '^GSPC',
      cme: 'SPX',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_REGULAR',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 5548.20,
    change: 42.60,
    changePercent: 0.77,
    high: 5560.40,
    low: 5518.30,
    open: 5522.10,
    previousClose: 5505.60,
    fiftyTwoWeekHigh: 5669.67,
    fiftyTwoWeekLow: 4103.78,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_index_ndx_nasdaq',
    symbol: 'NDX',
    displaySymbol: 'NDX',
    name: 'Nasdaq-100 Index',
    assetClass: 'INDEX',
    instrumentType: 'Cash Index',
    exchange: 'NASDAQ',
    exchangeMIC: 'XNAS',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'I:NDX',
    providerSymbols: {
      massive: 'I:NDX',
      yahoo: '^NDX',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_REGULAR',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 19520.40,
    change: 218.50,
    changePercent: 1.13,
    previousClose: 19301.90,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_index_vix_cboe',
    symbol: 'VIX',
    displaySymbol: 'VIX',
    name: 'CBOE Volatility Index',
    assetClass: 'INDEX',
    instrumentType: 'Volatility Index',
    exchange: 'CBOE',
    exchangeMIC: 'XCBO',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'I:VIX',
    providerSymbols: {
      massive: 'I:VIX',
      yahoo: '^VIX',
      cme: 'VIX',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_REGULAR',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 14.15,
    change: -0.71,
    changePercent: -4.78,
    high: 15.20,
    low: 13.90,
    previousClose: 14.86,
    fiftyTwoWeekHigh: 65.73,
    fiftyTwoWeekLow: 11.52,
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_index_dxy_ice',
    symbol: 'DXY',
    displaySymbol: 'DXY',
    name: 'US Dollar Index',
    assetClass: 'INDEX',
    instrumentType: 'Currency Index',
    exchange: 'ICE',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'DX-Y.NYB',
    providerSymbols: {
      yahoo: 'DX-Y.NYB',
      massive: 'I:DXY',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'REGULAR_24_5',
    activeStatus: 'ACTIVE',
    primaryProvider: 'yahoo',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 104.20,
    change: -0.29,
    changePercent: -0.28,
    previousClose: 104.49,
    lastUpdated: new Date().toISOString(),
  },

  // --- 4. FOREX CURRENCY PAIRS ---
  {
    instrumentId: 'inst_forex_eur_usd',
    symbol: 'EUR/USD',
    displaySymbol: 'EUR/USD',
    name: 'Euro / US Dollar',
    assetClass: 'FOREX',
    instrumentType: 'Major FX Currency Pair',
    exchange: 'FOREX Interbank OTC',
    exchangeMIC: 'FXCM',
    country: 'European Union / US',
    currency: 'USD',
    baseCurrency: 'EUR',
    quoteCurrency: 'USD',
    providerSymbol: 'C:EURUSD',
    providerSymbols: {
      massive: 'C:EURUSD',
      finnhub: 'OANDA:EUR_USD',
      yahoo: 'EURUSD=X',
      alpaca: 'EUR/USD',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'REGULAR_24_5',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 1.0894,
    change: 0.0031,
    changePercent: 0.29,
    bid: 1.0893,
    ask: 1.0895,
    spread: 0.0002,
    volume: 142000000,
    high: 1.0912,
    low: 1.0858,
    open: 1.0863,
    previousClose: 1.0863,
    fiftyTwoWeekHigh: 1.1215,
    fiftyTwoWeekLow: 1.0448,
    forexMetrics: {
      baseCurrency: 'EUR',
      quoteCurrency: 'USD',
      pipSize: 0.0001,
      spreadPips: 2.0,
      activeSession: 'NEW_YORK',
      sessionOverlap: 'London / New York Overlap',
      high24h: 1.0912,
      low24h: 1.0858,
    },
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_forex_gbp_usd',
    symbol: 'GBP/USD',
    displaySymbol: 'GBP/USD',
    name: 'British Pound / US Dollar',
    assetClass: 'FOREX',
    instrumentType: 'Major FX Currency Pair',
    exchange: 'FOREX Interbank OTC',
    country: 'United Kingdom / US',
    currency: 'USD',
    baseCurrency: 'GBP',
    quoteCurrency: 'USD',
    providerSymbol: 'C:GBPUSD',
    providerSymbols: {
      massive: 'C:GBPUSD',
      finnhub: 'OANDA:GBP_USD',
      yahoo: 'GBPUSD=X',
    },
    marketTimezone: 'Europe/London',
    tradingSession: 'REGULAR_24_5',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 1.2942,
    change: 0.0045,
    changePercent: 0.35,
    bid: 1.2941,
    ask: 1.2943,
    spread: 0.0002,
    volume: 98000000,
    high: 1.2965,
    low: 1.2880,
    previousClose: 1.2897,
    forexMetrics: {
      baseCurrency: 'GBP',
      quoteCurrency: 'USD',
      pipSize: 0.0001,
      spreadPips: 2.0,
      activeSession: 'LONDON',
      high24h: 1.2965,
      low24h: 1.2880,
    },
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_forex_usd_jpy',
    symbol: 'USD/JPY',
    displaySymbol: 'USD/JPY',
    name: 'US Dollar / Japanese Yen',
    assetClass: 'FOREX',
    instrumentType: 'Major FX Currency Pair',
    exchange: 'FOREX Interbank OTC',
    country: 'US / Japan',
    currency: 'JPY',
    baseCurrency: 'USD',
    quoteCurrency: 'JPY',
    providerSymbol: 'C:USDJPY',
    providerSymbols: {
      massive: 'C:USDJPY',
      finnhub: 'OANDA:USD_JPY',
      yahoo: 'USDJPY=X',
    },
    marketTimezone: 'Asia/Tokyo',
    tradingSession: 'REGULAR_24_5',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 154.62,
    change: -0.84,
    changePercent: -0.54,
    bid: 154.61,
    ask: 154.63,
    spread: 0.02,
    volume: 125000000,
    high: 155.80,
    low: 154.20,
    previousClose: 155.46,
    forexMetrics: {
      baseCurrency: 'USD',
      quoteCurrency: 'JPY',
      pipSize: 0.01,
      spreadPips: 2.0,
      activeSession: 'TOKYO',
      high24h: 155.80,
      low24h: 154.20,
    },
    lastUpdated: new Date().toISOString(),
  },

  // --- 5. CRYPTOCURRENCIES & TRADING PAIRS ---
  {
    instrumentId: 'inst_crypto_btc_usd',
    symbol: 'BTC/USD',
    displaySymbol: 'BTC/USD',
    name: 'Bitcoin',
    assetClass: 'CRYPTO_PAIR',
    instrumentType: 'Spot Cryptocurrency',
    exchange: 'Coinbase',
    country: 'Global Decentralized',
    currency: 'USD',
    baseCurrency: 'BTC',
    quoteCurrency: 'USD',
    providerSymbol: 'X:BTCUSD',
    providerSymbols: {
      massive: 'X:BTCUSD',
      finnhub: 'BINANCE:BTCUSDT',
      alpaca: 'BTC/USD',
      yahoo: 'BTC-USD',
    },
    marketTimezone: 'UTC',
    tradingSession: 'CONTINUOUS_24_7',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 64250.00,
    change: 1520.00,
    changePercent: 2.42,
    bid: 64245.00,
    ask: 64255.00,
    spread: 10.00,
    volume: 28400000000,
    high: 64980.00,
    low: 62450.00,
    open: 62730.00,
    previousClose: 62730.00,
    fiftyTwoWeekHigh: 73750.07,
    fiftyTwoWeekLow: 25980.12,
    marketCap: 1265000000000,
    cryptoMetrics: {
      baseAsset: 'BTC',
      quoteAsset: 'USD',
      exchangeName: 'Coinbase Pro / Aggregated',
      isAggregated: true,
      volume24hUsd: 28400000000,
      marketCapUsd: 1265000000000,
      circulatingSupply: 19740000,
      high24h: 64980.00,
      low24h: 62450.00,
    },
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_crypto_eth_usd',
    symbol: 'ETH/USD',
    displaySymbol: 'ETH/USD',
    name: 'Ethereum',
    assetClass: 'CRYPTO_PAIR',
    instrumentType: 'Spot Cryptocurrency',
    exchange: 'Coinbase',
    country: 'Global Decentralized',
    currency: 'USD',
    baseCurrency: 'ETH',
    quoteCurrency: 'USD',
    providerSymbol: 'X:ETHUSD',
    providerSymbols: {
      massive: 'X:ETHUSD',
      finnhub: 'BINANCE:ETHUSDT',
      alpaca: 'ETH/USD',
      yahoo: 'ETH-USD',
    },
    marketTimezone: 'UTC',
    tradingSession: 'CONTINUOUS_24_7',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 3480.50,
    change: 92.40,
    changePercent: 2.73,
    bid: 3480.00,
    ask: 3481.00,
    spread: 1.00,
    volume: 16800000000,
    high: 3520.00,
    low: 3360.00,
    previousClose: 3388.10,
    marketCap: 418000000000,
    cryptoMetrics: {
      baseAsset: 'ETH',
      quoteAsset: 'USD',
      exchangeName: 'Coinbase / Aggregated',
      isAggregated: true,
      volume24hUsd: 16800000000,
      marketCapUsd: 418000000000,
      circulatingSupply: 120200000,
      high24h: 3520.00,
      low24h: 3360.00,
    },
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_crypto_sol_usd',
    symbol: 'SOL/USD',
    displaySymbol: 'SOL/USD',
    name: 'Solana',
    assetClass: 'CRYPTO_PAIR',
    instrumentType: 'Spot Cryptocurrency',
    exchange: 'Coinbase',
    country: 'Global Decentralized',
    currency: 'USD',
    baseCurrency: 'SOL',
    quoteCurrency: 'USD',
    providerSymbol: 'X:SOLUSD',
    providerSymbols: {
      massive: 'X:SOLUSD',
      finnhub: 'BINANCE:SOLUSDT',
      alpaca: 'SOL/USD',
      yahoo: 'SOL-USD',
    },
    marketTimezone: 'UTC',
    tradingSession: 'CONTINUOUS_24_7',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 158.40,
    change: 7.20,
    changePercent: 4.76,
    volume: 4800000000,
    previousClose: 151.20,
    cryptoMetrics: {
      baseAsset: 'SOL',
      quoteAsset: 'USD',
      exchangeName: 'Coinbase / Aggregated',
      isAggregated: true,
      volume24hUsd: 4800000000,
      high24h: 162.10,
      low24h: 148.90,
    },
    lastUpdated: new Date().toISOString(),
  },

  // --- 6. CME FUTURES & COMMODITIES ---
  {
    instrumentId: 'inst_futures_es_cme',
    symbol: 'ES',
    displaySymbol: '/ES (E-mini S&P 500)',
    name: 'E-mini S&P 500 Futures',
    assetClass: 'FUTURES',
    instrumentType: 'Index Futures Contract',
    exchange: 'CME',
    exchangeMIC: 'XCME',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'ES=F',
    providerSymbols: {
      cme: '/ESH25',
      yahoo: 'ES=F',
      massive: 'ES',
    },
    marketTimezone: 'America/Chicago',
    tradingSession: 'US_FUTURES_CME',
    contractRoot: 'ES',
    contractMonth: 'Front Month Continuous',
    expirationDate: '2026-09-18',
    contractMultiplier: 50,
    settlementType: 'CASH',
    activeStatus: 'ACTIVE',
    primaryProvider: 'cme',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 5562.50,
    change: 45.25,
    changePercent: 0.82,
    bid: 5562.25,
    ask: 5562.75,
    spread: 0.50,
    volume: 1480000,
    high: 5575.00,
    low: 5512.25,
    open: 5520.00,
    previousClose: 5517.25,
    futuresMetrics: {
      contractRoot: 'ES',
      contractMonth: 'U26 (September 2026)',
      expirationDate: '2026-09-18',
      lastTradeDate: '2026-09-18 09:30 CT',
      multiplier: 50,
      tickSize: 0.25,
      tickValue: 12.50,
      settlementType: 'CASH',
      openInterest: 2640000,
      isContinuous: true,
      frontMonthSymbol: 'ESU26',
      daysToExpiration: 34,
      rollNotice: 'Next contract roll begins 8 days prior to expiry.',
    },
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_futures_nq_cme',
    symbol: 'NQ',
    displaySymbol: '/NQ (E-mini Nasdaq-100)',
    name: 'E-mini Nasdaq-100 Futures',
    assetClass: 'FUTURES',
    instrumentType: 'Index Futures Contract',
    exchange: 'CME',
    exchangeMIC: 'XCME',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'NQ=F',
    providerSymbols: {
      cme: '/NQH25',
      yahoo: 'NQ=F',
    },
    marketTimezone: 'America/Chicago',
    tradingSession: 'US_FUTURES_CME',
    contractRoot: 'NQ',
    contractMonth: 'Front Month Continuous',
    expirationDate: '2026-09-18',
    contractMultiplier: 20,
    settlementType: 'CASH',
    activeStatus: 'ACTIVE',
    primaryProvider: 'cme',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 19680.00,
    change: 232.00,
    changePercent: 1.19,
    volume: 620000,
    previousClose: 19448.00,
    futuresMetrics: {
      contractRoot: 'NQ',
      contractMonth: 'U26 (September 2026)',
      expirationDate: '2026-09-18',
      lastTradeDate: '2026-09-18 09:30 CT',
      multiplier: 20,
      tickSize: 0.25,
      tickValue: 5.00,
      settlementType: 'CASH',
      openInterest: 310000,
      isContinuous: true,
      frontMonthSymbol: 'NQU26',
      daysToExpiration: 34,
    },
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_commodity_cl_nymex',
    symbol: 'CL',
    displaySymbol: '/CL (Crude Oil)',
    name: 'WTI Crude Oil Futures',
    assetClass: 'COMMODITY',
    instrumentType: 'Physical Commodity Future',
    exchange: 'NYMEX',
    exchangeMIC: 'XNYM',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'CL=F',
    providerSymbols: {
      cme: '/CLH25',
      yahoo: 'CL=F',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_FUTURES_CME',
    contractRoot: 'CL',
    contractMultiplier: 1000, // 1,000 barrels
    settlementType: 'PHYSICAL',
    activeStatus: 'ACTIVE',
    primaryProvider: 'cme',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 78.50,
    change: -0.60,
    changePercent: -0.76,
    bid: 78.48,
    ask: 78.52,
    spread: 0.04,
    volume: 340000,
    high: 79.40,
    low: 77.90,
    previousClose: 79.10,
    futuresMetrics: {
      contractRoot: 'CL',
      contractMonth: 'Spot Active',
      expirationDate: '2026-09-20',
      lastTradeDate: '2026-09-20',
      multiplier: 1000,
      tickSize: 0.01,
      tickValue: 10.00,
      settlementType: 'PHYSICAL',
      openInterest: 1850000,
      isContinuous: true,
      frontMonthSymbol: 'CLV26',
      daysToExpiration: 36,
    },
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_commodity_gc_comex',
    symbol: 'GC',
    displaySymbol: '/GC (Gold Futures)',
    name: 'Gold Futures',
    assetClass: 'COMMODITY',
    instrumentType: 'Precious Metal Future',
    exchange: 'COMEX',
    exchangeMIC: 'XCEC',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'GC=F',
    providerSymbols: {
      cme: '/GCH25',
      yahoo: 'GC=F',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_FUTURES_CME',
    contractRoot: 'GC',
    contractMultiplier: 100, // 100 troy ounces
    settlementType: 'PHYSICAL',
    activeStatus: 'ACTIVE',
    primaryProvider: 'cme',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 2435.60,
    change: 8.40,
    changePercent: 0.35,
    volume: 185000,
    previousClose: 2427.20,
    futuresMetrics: {
      contractRoot: 'GC',
      contractMonth: 'Active Front',
      expirationDate: '2026-10-28',
      lastTradeDate: '2026-10-28',
      multiplier: 100,
      tickSize: 0.10,
      tickValue: 10.00,
      settlementType: 'PHYSICAL',
      openInterest: 540000,
      isContinuous: true,
      frontMonthSymbol: 'GCZ26',
      daysToExpiration: 74,
    },
    lastUpdated: new Date().toISOString(),
  },

  // --- 7. OPTIONS & INDEX OPTIONS ---
  {
    instrumentId: 'inst_opt_spy_260821_c515',
    symbol: 'SPY 260821 C515',
    displaySymbol: 'SPY $515.00 CALL (Aug 21, 2026)',
    name: 'SPY Aug 21, 2026 $515.00 Call Option',
    assetClass: 'OPTION',
    instrumentType: 'Vanilla Equity Call Option',
    exchange: 'CBOE / AMEX / ISE',
    country: 'United States',
    currency: 'USD',
    contractRoot: 'SPY',
    strikePrice: 515.00,
    expirationDate: '2026-08-21',
    optionType: 'CALL',
    contractMultiplier: 100,
    settlementType: 'PHYSICAL',
    providerSymbol: 'O:SPY260821C00515000',
    providerSymbols: {
      massive: 'O:SPY260821C00515000',
      yahoo: 'SPY260821C00515000',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_REGULAR',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 3.45,
    change: 0.85,
    changePercent: 32.69,
    bid: 3.40,
    ask: 3.50,
    spread: 0.10,
    volume: 184500,
    open: 2.60,
    previousClose: 2.60,
    greeks: {
      delta: 0.48,
      gamma: 0.045,
      theta: -0.062,
      vega: 0.18,
      rho: 0.035,
      iv: 13.8,
      ivPercentile: 24,
      openInterest: 142000,
      underlyingPrice: 512.48,
    },
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_opt_spy_260821_p505',
    symbol: 'SPY 260821 P505',
    displaySymbol: 'SPY $505.00 PUT (Aug 21, 2026)',
    name: 'SPY Aug 21, 2026 $505.00 Put Option',
    assetClass: 'OPTION',
    instrumentType: 'Vanilla Equity Put Option',
    exchange: 'CBOE',
    country: 'United States',
    currency: 'USD',
    contractRoot: 'SPY',
    strikePrice: 505.00,
    expirationDate: '2026-08-21',
    optionType: 'PUT',
    contractMultiplier: 100,
    settlementType: 'PHYSICAL',
    providerSymbol: 'O:SPY260821P00505000',
    providerSymbols: {
      massive: 'O:SPY260821P00505000',
      yahoo: 'SPY260821P00505000',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_REGULAR',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 1.85,
    change: -0.45,
    changePercent: -19.56,
    bid: 1.80,
    ask: 1.90,
    spread: 0.10,
    volume: 124000,
    previousClose: 2.30,
    greeks: {
      delta: -0.28,
      gamma: 0.038,
      theta: -0.054,
      vega: 0.14,
      iv: 14.5,
      openInterest: 198000,
      underlyingPrice: 512.48,
    },
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_opt_spx_260821_c5550',
    symbol: 'SPX 260821 C5550',
    displaySymbol: 'SPX $5,550.00 European Call Option',
    name: 'S&P 500 Index Cash-Settled Call Option',
    assetClass: 'INDEX_OPTION',
    instrumentType: 'Index Option (Cash-Settled / Section 1256)',
    exchange: 'CBOE',
    country: 'United States',
    currency: 'USD',
    contractRoot: 'SPX',
    strikePrice: 5550.00,
    expirationDate: '2026-08-21',
    optionType: 'CALL',
    contractMultiplier: 100,
    settlementType: 'CASH',
    providerSymbol: 'O:SPX260821C05550000',
    providerSymbols: {
      massive: 'O:SPX260821C05550000',
      cme: 'SPX260821C5550',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'US_EQUITIES_REGULAR',
    activeStatus: 'ACTIVE',
    primaryProvider: 'massive',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 24.50,
    change: 6.20,
    changePercent: 33.88,
    bid: 24.20,
    ask: 24.80,
    spread: 0.60,
    volume: 84000,
    previousClose: 18.30,
    greeks: {
      delta: 0.52,
      gamma: 0.0042,
      theta: -0.85,
      vega: 1.95,
      iv: 12.9,
      openInterest: 42000,
      underlyingPrice: 5548.20,
    },
    lastUpdated: new Date().toISOString(),
  },

  // --- 8. FIXED INCOME & TREASURIES ---
  {
    instrumentId: 'inst_treasury_us10y',
    symbol: 'US10Y',
    displaySymbol: 'US 10-Year Benchmark Yield',
    name: 'United States 10-Year Treasury Yield',
    assetClass: 'TREASURY',
    instrumentType: 'Government Benchmark Yield',
    exchange: 'US Treasury / Primary Dealers',
    country: 'United States',
    currency: 'USD',
    providerSymbol: '^TNX',
    providerSymbols: {
      yahoo: '^TNX',
      fred: 'DGS10',
      massive: 'I:TNX',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'BOND_SIFMA',
    activeStatus: 'ACTIVE',
    primaryProvider: 'yahoo',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 4.28,
    change: -0.07,
    changePercent: -1.61,
    high: 4.35,
    low: 4.26,
    previousClose: 4.35,
    fiftyTwoWeekHigh: 4.99,
    fiftyTwoWeekLow: 3.79,
    bondMetrics: {
      couponRate: 4.25,
      maturityDate: '2036-08-15',
      yieldToMaturity: 4.28,
      durationYears: 8.6,
      benchmarkSpreadBps: 0,
      rating: 'AAA / AA+',
      issuer: 'United States Department of the Treasury',
    },
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_treasury_us02y',
    symbol: 'US02Y',
    displaySymbol: 'US 2-Year Treasury Yield',
    name: 'United States 2-Year Treasury Yield',
    assetClass: 'TREASURY',
    instrumentType: 'Short-Term Government Note Yield',
    exchange: 'US Treasury',
    country: 'United States',
    currency: 'USD',
    providerSymbol: '2YY=F',
    providerSymbols: {
      yahoo: '2YY=F',
      fred: 'DGS2',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'BOND_SIFMA',
    activeStatus: 'ACTIVE',
    primaryProvider: 'yahoo',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 4.62,
    change: -0.05,
    changePercent: -1.07,
    previousClose: 4.67,
    bondMetrics: {
      couponRate: 4.625,
      maturityDate: '2028-08-31',
      yieldToMaturity: 4.62,
      durationYears: 1.9,
      benchmarkSpreadBps: 34, // Yield curve inversion: 2Y-10Y = +34 bps
      rating: 'AAA / AA+',
      issuer: 'United States Department of the Treasury',
    },
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_bond_corp_hyg',
    symbol: 'HY_OAS',
    displaySymbol: 'US High Yield Option-Adjusted Spread',
    name: 'ICE BofA US High Yield Index OAS',
    assetClass: 'BOND',
    instrumentType: 'Corporate Credit Benchmark',
    exchange: 'ICE / SIFMA',
    country: 'United States',
    currency: 'USD',
    providerSymbol: 'BAMLH0A0HYM2',
    providerSymbols: {
      fred: 'BAMLH0A0HYM2',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'BOND_SIFMA',
    activeStatus: 'ACTIVE',
    primaryProvider: 'fred',
    realTimeStatus: 'END_OF_DAY',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 3.15,
    change: -0.08,
    changePercent: -2.48,
    previousClose: 3.23,
    bondMetrics: {
      couponRate: 6.85,
      maturityDate: 'Blended 6.2Y',
      yieldToMaturity: 7.43,
      benchmarkSpreadBps: 315,
      rating: 'BB / B Blended',
      issuer: 'US Corporate High Yield Composite',
    },
    lastUpdated: new Date().toISOString(),
  },

  // --- 9. MACRO ECONOMIC INDICATORS ---
  {
    instrumentId: 'inst_macro_cpi_mom',
    symbol: 'CPI_MOM',
    displaySymbol: 'Core CPI (MoM)',
    name: 'Consumer Price Index: Core Month-over-Month',
    assetClass: 'ECONOMIC_INDICATOR',
    instrumentType: 'Macroeconomic Index Release',
    exchange: 'Bureau of Labor Statistics (BLS)',
    country: 'United States',
    currency: '%',
    providerSymbol: 'CPILFESL',
    providerSymbols: {
      fred: 'CPILFESL',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'MACRO_SCHEDULED',
    activeStatus: 'ACTIVE',
    primaryProvider: 'fred',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 0.20,
    change: -0.10,
    changePercent: -33.33,
    economicMetrics: {
      frequency: 'MONTHLY',
      lastReading: '0.2%',
      consensusForecast: '0.2%',
      priorReading: '0.3%',
      unit: '% MoM Seasonally Adjusted',
      importance: 'EXTREME',
      nextReleaseDate: 'September 11, 2026 08:30 ET',
      sourceAgency: 'U.S. Bureau of Labor Statistics',
    },
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_macro_fed_funds',
    symbol: 'FED_FUNDS',
    displaySymbol: 'Federal Funds Effective Rate',
    name: 'Federal Funds Target Rate Range',
    assetClass: 'ECONOMIC_INDICATOR',
    instrumentType: 'Central Bank Policy Rate',
    exchange: 'Federal Reserve Board',
    country: 'United States',
    currency: '%',
    providerSymbol: 'FEDFUNDS',
    providerSymbols: {
      fred: 'FEDFUNDS',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'MACRO_SCHEDULED',
    activeStatus: 'ACTIVE',
    primaryProvider: 'fred',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 5.33,
    change: 0.00,
    changePercent: 0.00,
    economicMetrics: {
      frequency: 'DAILY',
      lastReading: '5.25% - 5.50%',
      consensusForecast: 'Hold at 5.25%-5.50%',
      priorReading: '5.25% - 5.50%',
      unit: '% p.a.',
      importance: 'EXTREME',
      nextReleaseDate: 'September 18, 2026 14:00 ET',
      sourceAgency: 'Federal Open Market Committee (FOMC)',
    },
    lastUpdated: new Date().toISOString(),
  },
  {
    instrumentId: 'inst_macro_nfp',
    symbol: 'NFP',
    displaySymbol: 'Non-Farm Payrolls (NFP)',
    name: 'US Total Nonfarm Payroll Employment',
    assetClass: 'ECONOMIC_INDICATOR',
    instrumentType: 'Labor Market Indicator',
    exchange: 'Bureau of Labor Statistics (BLS)',
    country: 'United States',
    currency: 'K',
    providerSymbol: 'PAYEMS',
    providerSymbols: {
      fred: 'PAYEMS',
    },
    marketTimezone: 'America/New_York',
    tradingSession: 'MACRO_SCHEDULED',
    activeStatus: 'ACTIVE',
    primaryProvider: 'fred',
    realTimeStatus: 'REAL_TIME',
    feedDelayMinutes: 0,
    isEntitled: true,
    price: 185.00,
    change: 10.00,
    changePercent: 5.71,
    economicMetrics: {
      frequency: 'MONTHLY',
      lastReading: '185K',
      consensusForecast: '175K',
      priorReading: '175K',
      unit: 'Thousands of Jobs Added',
      importance: 'EXTREME',
      nextReleaseDate: 'September 06, 2026 08:30 ET',
      sourceAgency: 'U.S. Bureau of Labor Statistics',
    },
    lastUpdated: new Date().toISOString(),
  },
];

export const MASTER_INSTRUMENTS: NormalizedInstrument[] = [
  ...BASE_MASTER_INSTRUMENTS,
  ...ADDITIONAL_INSTRUMENTS,
];

export class InstrumentDirectoryService {
  private static directory: Map<string, NormalizedInstrument> = new Map();
  private static symbolIndex: Map<string, NormalizedInstrument> = new Map();

  static {
    // 1. Populate directory and primary exact symbols first
    for (const inst of MASTER_INSTRUMENTS) {
      this.directory.set(inst.instrumentId, inst);
      this.symbolIndex.set(inst.symbol.toUpperCase(), inst);
    }

    // 2. Populate aliases, display tickers, and provider symbols without overriding primary symbols
    for (const inst of MASTER_INSTRUMENTS) {
      const disp = inst.displaySymbol.toUpperCase();
      if (!this.symbolIndex.has(disp)) {
        this.symbolIndex.set(disp, inst);
      }
      if (inst.providerSymbol) {
        const prov = inst.providerSymbol.toUpperCase();
        if (!this.symbolIndex.has(prov)) {
          this.symbolIndex.set(prov, inst);
        }
      }
      if (inst.providerSymbols?.yahoo) {
        const y = inst.providerSymbols.yahoo.toUpperCase();
        if (!this.symbolIndex.has(y)) {
          this.symbolIndex.set(y, inst);
        }
      }
      if (inst.providerSymbols?.massive) {
        const m = inst.providerSymbols.massive.toUpperCase();
        if (!this.symbolIndex.has(m)) {
          this.symbolIndex.set(m, inst);
        }
      }
      if (inst.providerSymbols?.alpaca) {
        const a = inst.providerSymbols.alpaca.toUpperCase();
        if (!this.symbolIndex.has(a)) {
          this.symbolIndex.set(a, inst);
        }
      }
      if (inst.providerSymbols?.fred) {
        const f = inst.providerSymbols.fred.toUpperCase();
        if (!this.symbolIndex.has(f)) {
          this.symbolIndex.set(f, inst);
        }
      }
      if (inst.symbol.startsWith('ECON:')) {
        const econKey = inst.symbol.replace('ECON:', '').toUpperCase();
        if (!this.symbolIndex.has(econKey)) {
          this.symbolIndex.set(econKey, inst);
        }
      }
    }
  }

  // Find instrument by ID
  public static getById(instrumentId: string): NormalizedInstrument | null {
    const existing = this.directory.get(instrumentId);
    if (existing) return existing;

    try {
      const { InstrumentStore } = require('../../server/instrumentStore');
      const dbInst = InstrumentStore.getById(instrumentId);
      if (dbInst) {
        return InstrumentStore.toNormalizedInstrument(dbInst);
      }
    } catch {}

    return null;
  }

  // Find instrument by Ticker symbol or provider symbol
  public static getBySymbol(symbol: string): NormalizedInstrument | null {
    if (!symbol) return null;
    const clean = symbol.trim().toUpperCase();
    const existing = this.symbolIndex.get(clean);
    if (existing) return existing;

    try {
      const { InstrumentStore } = require('../../server/instrumentStore');
      const dbInst = InstrumentStore.getBySymbol(clean);
      if (dbInst) {
        return InstrumentStore.toNormalizedInstrument(dbInst);
      }
    } catch {}

    return null;
  }

  // Get all instruments in directory
  public static getAll(): NormalizedInstrument[] {
    return Array.from(this.directory.values());
  }

  // Filter by asset class
  public static getByAssetClass(assetClass: UniversalAssetClass): NormalizedInstrument[] {
    return this.getAll().filter((inst) => inst.assetClass === assetClass);
  }

  // Universal Search with Fuzzy Matching and Grouping across 5000+ catalog
  public static search(
    query: string,
    assetClassFilter?: UniversalAssetClass,
    limit = 50
  ): {
    results: NormalizedInstrument[];
    groupedResults: InstrumentSearchResultGroup[];
    totalCount: number;
  } {
    const q = (query || '').trim().toLowerCase();
    const seenSymbols = new Set<string>();
    const combined: NormalizedInstrument[] = [];

    const cleanQ = q.replace(/[^a-z0-9]/g, '');

    // 1. Search local master instruments
    const localMatches = this.getAll().filter((inst) => {
      if (assetClassFilter && inst.assetClass !== assetClassFilter) {
        return false;
      }
      if (!q) return true;
      const sym = inst.symbol.toLowerCase();
      const disp = inst.displaySymbol.toLowerCase();
      const prov = (inst.providerSymbol || '').toLowerCase();
      const name = inst.name.toLowerCase();

      // Alias handling for common trading queries
      if (q === '/es' && (sym === 'es=f' || prov === 'es=f')) return true;
      if (q === 'us10y' && (sym === '^tnx' || prov === '^tnx')) return true;
      if (cleanQ === 'bitcoin' && (sym === 'btc-usd' || disp === 'btc/usd' || prov === 'btc-usd')) return true;

      return (
        sym.includes(q) ||
        disp.includes(q) ||
        prov.includes(q) ||
        name.includes(q) ||
        inst.exchange.toLowerCase().includes(q) ||
        inst.assetClass.toLowerCase().includes(q) ||
        inst.instrumentType.toLowerCase().includes(q) ||
        (inst.baseCurrency && inst.baseCurrency.toLowerCase().includes(q)) ||
        (inst.quoteCurrency && inst.quoteCurrency.toLowerCase().includes(q)) ||
        (inst.contractRoot && inst.contractRoot.toLowerCase().includes(q)) ||
        (inst.isin && inst.isin.toLowerCase().includes(q)) ||
        (inst.cusip && inst.cusip.toLowerCase().includes(q))
      );
    });

    for (const inst of localMatches) {
      const sym = inst.symbol.toUpperCase();
      if (!seenSymbols.has(sym)) {
        seenSymbols.add(sym);
        combined.push(inst);
      }
    }

    // 2. Search 5000+ Universe Store if applicable
    try {
      const { InstrumentStore } = require('../../server/instrumentStore');
      const storeResults = InstrumentStore.search(query, {
        limit: 50,
        assetType: assetClassFilter === 'ETF' ? 'ETF' : assetClassFilter === 'STOCK' ? 'STOCK' : undefined,
      });

      for (const dbInst of storeResults) {
        const sym = dbInst.symbol.toUpperCase();
        if (!seenSymbols.has(sym)) {
          seenSymbols.add(sym);
          combined.push(InstrumentStore.toNormalizedInstrument(dbInst));
        }
      }
    } catch {}

    // 3. Sort with strict precision ranking
    // 1st: Exact symbol match
    // 2nd: Starts with symbol
    // 3rd: Name starts with word
    // 4th: Contains query
    combined.sort((a, b) => {
      const aSym = a.symbol.toLowerCase();
      const bSym = b.symbol.toLowerCase();
      const aName = a.name.toLowerCase();
      const bName = b.name.toLowerCase();

      if (aSym === q && bSym !== q) return -1;
      if (bSym === q && aSym !== q) return 1;

      if (aSym.startsWith(q) && !bSym.startsWith(q)) return -1;
      if (bSym.startsWith(q) && !aSym.startsWith(q)) return 1;

      const aNameStarts = aName.startsWith(q);
      const bNameStarts = bName.startsWith(q);
      if (aNameStarts && !bNameStarts) return -1;
      if (bNameStarts && !aNameStarts) return 1;

      return aSym.localeCompare(bSym);
    });

    const finalResults = combined.slice(0, limit);

    return {
      results: finalResults,
      groupedResults: this.groupInstruments(finalResults),
      totalCount: combined.length,
    };
  }

  // Helper to group search results into logical asset class categories
  public static groupInstruments(instruments: NormalizedInstrument[]): InstrumentSearchResultGroup[] {
    const groups: Record<string, { title: string; assetClass: UniversalAssetClass; items: NormalizedInstrument[] }> = {
      STOCKS: { title: 'Stocks & Equities', assetClass: 'STOCK', items: [] },
      ETFS_FUNDS: { title: 'ETFs & Mutual Funds', assetClass: 'ETF', items: [] },
      OPTIONS: { title: 'Options & Derivatives', assetClass: 'OPTION', items: [] },
      FOREX: { title: 'Forex Currencies', assetClass: 'FOREX', items: [] },
      CRYPTO: { title: 'Cryptocurrencies', assetClass: 'CRYPTO_PAIR', items: [] },
      FUTURES: { title: 'Futures Contracts', assetClass: 'FUTURES', items: [] },
      COMMODITIES: { title: 'Commodities & Metals', assetClass: 'COMMODITY', items: [] },
      INDEXES: { title: 'Stock Indexes & Benchmarks', assetClass: 'INDEX', items: [] },
      FIXED_INCOME: { title: 'Treasuries & Fixed Income', assetClass: 'TREASURY', items: [] },
      MACRO: { title: 'Macro Economic Indicators', assetClass: 'ECONOMIC_INDICATOR', items: [] },
    };

    for (const inst of instruments) {
      if (inst.assetClass === 'STOCK' || inst.assetClass === 'ADR' || inst.assetClass === 'WARRANT') {
        groups.STOCKS.items.push(inst);
      } else if (inst.assetClass === 'ETF' || inst.assetClass === 'FUND') {
        groups.ETFS_FUNDS.items.push(inst);
      } else if (inst.assetClass === 'OPTION' || inst.assetClass === 'INDEX_OPTION' || inst.assetClass === 'FUTURES_OPTION') {
        groups.OPTIONS.items.push(inst);
      } else if (inst.assetClass === 'FOREX') {
        groups.FOREX.items.push(inst);
      } else if (inst.assetClass === 'CRYPTO' || inst.assetClass === 'CRYPTO_PAIR') {
        groups.CRYPTO.items.push(inst);
      } else if (inst.assetClass === 'FUTURES') {
        groups.FUTURES.items.push(inst);
      } else if (inst.assetClass === 'COMMODITY') {
        groups.COMMODITIES.items.push(inst);
      } else if (inst.assetClass === 'INDEX') {
        groups.INDEXES.items.push(inst);
      } else if (inst.assetClass === 'TREASURY' || inst.assetClass === 'BOND') {
        groups.FIXED_INCOME.items.push(inst);
      } else if (inst.assetClass === 'ECONOMIC_INDICATOR') {
        groups.MACRO.items.push(inst);
      }
    }

    return Object.values(groups)
      .filter((g) => g.items.length > 0)
      .map((g) => ({
        assetClass: g.assetClass,
        title: g.title,
        instruments: g.items,
      }));
  }

  // Register or update an instrument in the directory
  public static registerInstrument(instrument: NormalizedInstrument): void {
    this.directory.set(instrument.instrumentId, instrument);
    this.symbolIndex.set(instrument.symbol.toUpperCase(), instrument);
    this.symbolIndex.set(instrument.displaySymbol.toUpperCase(), instrument);
    if (instrument.providerSymbol) {
      this.symbolIndex.set(instrument.providerSymbol.toUpperCase(), instrument);
    }
  }
}
