import { PlanFeatureConfig, SubscriptionPlanId } from '../types/subscription';

export const TRIAL_DURATION_DAYS = 15;

export const SUBSCRIPTION_PLANS: Record<SubscriptionPlanId, PlanFeatureConfig> = {
  free: {
    id: 'free',
    name: 'Free',
    monthlyPrice: 0,
    annualMonthlyPrice: 0,
    annualBilledTotal: 0,
    trialDays: 0,
    description: 'Experience core market feeds and AI insights before subscribing.',
    features: [
      'Basic stock market dashboard & quotes',
      'Delayed market data where required',
      'Basic interactive chart with core indicators',
      'Basic support & resistance levels',
      'Basic Bullish / Bearish / Neutral bias',
      'Basic Risk Meter score',
      'Limited Gemini AI assistant (5 requests/day)',
      'Limited "Why Is It Moving?" summary',
      '1 Watchlist (up to 5 stocks)',
      'Up to 3 active price alerts',
      '7-day prediction history log',
      'Basic economic calendar & market news',
    ],
    limits: {
      maxAIRequestsPerDay: 5,
      maxWatchlists: 1,
      maxWatchlistTickers: 5,
      maxAlerts: 3,
      predictionHistoryDays: 7,
      timeframes: ['1d', '1w'],
      canUseRealtimeData: false,
      canUseAdvancedAI: false,
      canUseOptions: false,
      canUseAdvancedOptions: false,
      canUseUnusualOptions: false,
      canUseScanner: false,
      scannerLevel: 'none',
      canUseBacktesting: false,
      backtestingLevel: 'none',
      canUseSimilarSignals: false,
      canUsePredictionAccuracy: false,
      canCreateAdvancedAlerts: false,
      canExportReports: false,
      canExportAdvancedData: false,
      canAccessApiKeys: false,
      hasPrioritySupport: false,
      canUseConnectedPortfolio: false,
      canUseRiskGuardian: false,
      maxConnectedAccounts: 0,
    },
  },
  basic: {
    id: 'basic',
    name: 'Basic',
    monthlyPrice: 9.99,
    annualMonthlyPrice: 7.99,
    annualBilledTotal: 95.88,
    trialDays: 15,
    description: 'Affordable toolkit for regular investors & beginner swing traders.',
    features: [
      'Everything in Free',
      '1 Connected Brokerage Account (Read-Only)',
      'Basic Portfolio Intelligence & Holdings sync',
      'Expanded market data access',
      'Full technical indicators (VWAP, EMA 9/20/50/200, SMA, RSI, MACD, BB)',
      'Full support & resistance with confirmation & invalidation levels',
      'AI market explanations & setup grades',
      'Full "Why Is It Moving?" market drivers',
      'Standard probability analysis & Risk Meter',
      'Basic stock scanner & sector breakdown',
      'Basic market breadth & economic impact ratings',
      'AI News sentiment & catalyst breakdown',
      'Up to 25 Gemini AI requests per day',
      'Up to 2 watchlists (25 total stocks)',
      'Up to 15 active market alerts',
      '30-day prediction history',
      'Multi-timeframe analysis (15m, 1h, Today)',
    ],
    limits: {
      maxAIRequestsPerDay: 25,
      maxWatchlists: 2,
      maxWatchlistTickers: 25,
      maxAlerts: 15,
      predictionHistoryDays: 30,
      timeframes: ['15m', '1h', '4h', '1d', '1w'],
      canUseRealtimeData: false,
      canUseAdvancedAI: false,
      canUseOptions: false,
      canUseAdvancedOptions: false,
      canUseUnusualOptions: false,
      canUseScanner: true,
      scannerLevel: 'basic',
      canUseBacktesting: false,
      backtestingLevel: 'none',
      canUseSimilarSignals: false,
      canUsePredictionAccuracy: false,
      canCreateAdvancedAlerts: false,
      canExportReports: true,
      canExportAdvancedData: false,
      canAccessApiKeys: false,
      hasPrioritySupport: false,
      canUseConnectedPortfolio: true,
      canUseRiskGuardian: false,
      maxConnectedAccounts: 1,
    },
  },
  pro: {
    id: 'pro',
    name: 'Pro',
    badge: 'MOST POPULAR',
    isPopular: true,
    monthlyPrice: 29.99,
    annualMonthlyPrice: 24.99,
    annualBilledTotal: 299.88,
    trialDays: 15,
    description: 'For active traders seeking real-time data, advanced AI & quantitative backtesting.',
    features: [
      'Everything in Basic',
      'Up to 5 Connected Brokerage Accounts',
      'MarketMind Connected Portfolio™ with Risk Guardian™',
      'Portfolio "Why Is It Moving?" real-time attribution',
      'Portfolio Correlation Matrix & Sector Concentration alerts',
      'Real-time market data stream (sub-second feeds where licensed)',
      'Advanced multi-timeframe overlays (5m, 15m, 30m, 1h, 4h, Today, Next Day, 5-Day)',
      'Advanced Bullish/Bearish probability matrix',
      'Full 8-Factor signal breakdown (Technical, Price Action, Volume, Breadth, Macro, News, Options, Intermarket)',
      'Advanced Risk Meter & Volatility surface',
      'Prediction Accuracy dashboard & Brier score',
      'Similar Historical Signals matching engine',
      'Probability Calibration curve',
      'Advanced high-speed stock scanner & heatmaps',
      'Basic options intelligence & Put/Call ratios',
      'Limited quantitative backtesting engine',
      'Advanced Gemini 3.7 Flash AI assistant (100 requests/day)',
      '3 AI persona modes (Beginner, Standard, Advanced)',
      'Up to 10 watchlists (100 total stocks)',
      'Up to 75 active alerts with Webhook triggers',
      '1 Year (365 days) prediction history log',
      'Standard CSV/PDF data export',
    ],
    limits: {
      maxAIRequestsPerDay: 100,
      maxWatchlists: 10,
      maxWatchlistTickers: 100,
      maxAlerts: 75,
      predictionHistoryDays: 365,
      timeframes: ['1m', '2m', '5m', '15m', '30m', '1h', '4h', '1d', '5d', '1w'],
      canUseRealtimeData: true,
      canUseAdvancedAI: true,
      canUseOptions: true,
      canUseAdvancedOptions: false,
      canUseUnusualOptions: false,
      canUseScanner: true,
      scannerLevel: 'advanced',
      canUseBacktesting: true,
      backtestingLevel: 'limited',
      canUseSimilarSignals: true,
      canUsePredictionAccuracy: true,
      canCreateAdvancedAlerts: true,
      canExportReports: true,
      canExportAdvancedData: false,
      canAccessApiKeys: true,
      hasPrioritySupport: false,
      canUseConnectedPortfolio: true,
      canUseRiskGuardian: true,
      maxConnectedAccounts: 5,
    },
  },
  premium: {
    id: 'premium',
    name: 'Premium',
    badge: 'FULL QUANT POWER',
    monthlyPrice: 69.99,
    annualMonthlyPrice: 59.99,
    annualBilledTotal: 719.88,
    trialDays: 15,
    description: 'Institutional-grade options intelligence, dark pool gamma flow & full backtesting.',
    features: [
      'Everything in Pro',
      'Unlimited Connected Brokerage Accounts',
      'Full Portfolio Stress Testing & Custom Macro Scenarios',
      'Institutional Options Greeks, Theta Burn & DTE Radar',
      'Portfolio News & Earnings Proximity Feed',
      'Dividend Intelligence & Projected Income Flow',
      'Advanced options intelligence: Put/Call ratios, Open Interest, IV & Expected Move',
      'Major option strike magnets & pinning levels',
      'Unusual Options Activity & Dark Pool gamma flow radar',
      'Advanced options-related price zones & max pain',
      'Advanced real-time stock scanner with custom filter formulas',
      'Advanced multi-year backtesting & statistical verification',
      'Full prediction history (unlimited / 730+ days)',
      'Advanced similar-market-condition analytics',
      'Advanced market breadth & sector rotation radar',
      'Advanced intermarket cross-asset correlation models',
      'Advanced AI market macro reports & executive briefs',
      '300 Gemini AI requests/day (priority compute cluster)',
      'Unlimited watchlists (up to 500 stocks)',
      'Up to 250 active multi-channel alerts (Telegram, Discord, Webhooks)',
      'Advanced raw data export (JSON/CSV/API feeds)',
      'Priority 24/7 technical support & custom indicator scripting',
    ],
    limits: {
      maxAIRequestsPerDay: 300,
      maxWatchlists: 50,
      maxWatchlistTickers: 500,
      maxAlerts: 250,
      predictionHistoryDays: 730,
      timeframes: ['1m', '2m', '5m', '15m', '30m', '1h', '4h', '1d', '5d', '1w'],
      canUseRealtimeData: true,
      canUseAdvancedAI: true,
      canUseOptions: true,
      canUseAdvancedOptions: true,
      canUseUnusualOptions: true,
      canUseScanner: true,
      scannerLevel: 'premium',
      canUseBacktesting: true,
      backtestingLevel: 'advanced',
      canUseSimilarSignals: true,
      canUsePredictionAccuracy: true,
      canCreateAdvancedAlerts: true,
      canExportReports: true,
      canExportAdvancedData: true,
      canAccessApiKeys: true,
      hasPrioritySupport: true,
      canUseConnectedPortfolio: true,
      canUseRiskGuardian: true,
      maxConnectedAccounts: 50,
    },
  },
};

export const DEFAULT_PLAN: SubscriptionPlanId = 'pro';

