import { PlanFeatureConfig, SubscriptionPlanId } from '../types/subscription';

export const TRIAL_DURATION_DAYS = 15;

/**
 * Deep Research and AI Computation Cost Control Guardrails
 */
export const DEEP_RESEARCH_COST_LIMITS = {
  TIMEOUT_MS: 45000, // 45-second execution timeout guard
  DEFAULT_MAX_SOURCES: 12,
  DEFAULT_MAX_STEPS: 10,
  DEFAULT_MAX_TOKENS: 15000,
};

export const SUBSCRIPTION_PLANS: Record<SubscriptionPlanId, PlanFeatureConfig> = {
  free: {
    id: 'free',
    name: 'Free Explorer',
    monthlyPrice: 0,
    annualMonthlyPrice: 0,
    annualBilledTotal: 0,
    annualSavingsPercent: 0,
    trialDays: 15,
    description: 'Essential market quotes, basic indicators, and sample AI capabilities.',
    features: [
      'Basic stock market dashboard & quotes',
      'Delayed market data where required',
      'Standard interactive charts with core indicators',
      'Basic support & resistance dynamic pivots',
      'Basic Bullish / Bearish / Neutral trend bias',
      'Basic Risk Meter score',
      'Ask MarketMind AI (5 queries/day)',
      'Basic Deep Research (1 report/mo, max 3 sources)',
      '1 Watchlist (up to 5 tickers)',
      'Up to 3 active price alerts',
      '1 Saved research report',
      'Community discussion access',
    ],
    limits: {
      maxAIRequestsPerDay: 5,
      maxMonthlyDeepResearchJobs: 1,
      maxDeepResearchSourcesPerJob: 3,
      maxDeepResearchAiSteps: 3,
      maxDeepResearchTokens: 2500,
      maxSavedResearchReports: 1,
      maxWatchlists: 1,
      maxWatchlistTickers: 5,
      maxAlerts: 3,
      predictionHistoryDays: 7,
      timeframes: ['1d', '1w'],
      canUseRealtimeData: false,
      canUseAdvancedAI: false,
      canUseOptions: false,
      canUseAdvancedOptions: false,
      canUseUnusualOptions: false,
      canUseScanner: false,
      scannerLevel: 'none',
      canUseBacktesting: false,
      backtestingLevel: 'none',
      canUseSimilarSignals: false,
      canUsePredictionAccuracy: false,
      canCreateAdvancedAlerts: false,
      canExportReports: false,
      canExportAdvancedData: false,
      canExportPdfResearch: false,
      canUseSecResearch: false,
      canUseEarningsTranscripts: false,
      canUseMacroResearch: false,
      canUseWhatChanged: false,
      hasPriorityResearchQueue: false,
      hasEarlyAccessFeatures: false,
      canAccessApiKeys: false,
      hasPrioritySupport: false,
      canUseConnectedPortfolio: false,
      canUseRiskGuardian: false,
      maxConnectedAccounts: 0,
    },
  },

  basic: {
    id: 'basic',
    name: 'Basic',
    monthlyPrice: 9.99,
    annualMonthlyPrice: 8.25,
    annualBilledTotal: 99.00,
    annualSavingsPercent: 17.5,
    trialDays: 15,
    description: 'Affordable toolkit for beginning and casual investors starting their market journey.',
    features: [
      'Everything in Free',
      '1 Connected Brokerage Account (Read-Only)',
      'Standard stock research & basic portfolio tracking',
      'Expanded market data & economic calendar',
      'Core technical indicators (VWAP, EMA 9/20/50/200, RSI, MACD)',
      'Ask MarketMind AI (20 requests/day)',
      'Deep Research (3 reports/mo, max 6 sources per job)',
      'Basic stock scanner & sector heatmaps',
      'AI News sentiment analysis & market drivers',
      '3 Watchlists (up to 25 tickers each)',
      'Up to 10 active market price alerts',
      '10 Saved research reports',
      '30-day prediction history log',
      'Standard CSV report export',
    ],
    limits: {
      maxAIRequestsPerDay: 20,
      maxMonthlyDeepResearchJobs: 3,
      maxDeepResearchSourcesPerJob: 6,
      maxDeepResearchAiSteps: 5,
      maxDeepResearchTokens: 6000,
      maxSavedResearchReports: 10,
      maxWatchlists: 3,
      maxWatchlistTickers: 25,
      maxAlerts: 10,
      predictionHistoryDays: 30,
      timeframes: ['15m', '1h', '4h', '1d', '1w'],
      canUseRealtimeData: false,
      canUseAdvancedAI: false,
      canUseOptions: false,
      canUseAdvancedOptions: false,
      canUseUnusualOptions: false,
      canUseScanner: true,
      scannerLevel: 'basic',
      canUseBacktesting: false,
      backtestingLevel: 'none',
      canUseSimilarSignals: false,
      canUsePredictionAccuracy: false,
      canCreateAdvancedAlerts: false,
      canExportReports: true,
      canExportAdvancedData: false,
      canExportPdfResearch: false,
      canUseSecResearch: false,
      canUseEarningsTranscripts: false,
      canUseMacroResearch: false,
      canUseWhatChanged: false,
      hasPriorityResearchQueue: false,
      hasEarlyAccessFeatures: false,
      canAccessApiKeys: false,
      hasPrioritySupport: false,
      canUseConnectedPortfolio: true,
      canUseRiskGuardian: false,
      maxConnectedAccounts: 1,
    },
  },

  pro: {
    id: 'pro',
    name: 'Pro',
    badge: 'MOST POPULAR',
    isPopular: true,
    monthlyPrice: 29.99,
    annualMonthlyPrice: 16.58,
    annualBilledTotal: 199.00,
    annualSavingsPercent: 17,
    trialDays: 15,
    description: 'Designed for active retail investors who need real-time streams and advanced analytics.',
    features: [
      'Everything in Basic',
      'Real-time tick-by-tick WebSocket market stream',
      'Up to 5 Connected Brokerage Accounts with Risk Guardian™',
      'Ask MarketMind AI (100 requests/day with multi-persona modes)',
      'Why Is It Moving analysis',
      'Deep Research (15 reports/mo, max 12 sources per job)',
      'Bull vs Bear scenario research & probability calibration',
      'Advanced earnings intelligence & conference call transcripts',
      'Macro trends, sector rotation & interest rate sensitivity',
      'Investment memo generation & why-is-it-moving real-time attribution',
      'Advanced technical analysis & multi-timeframe overlays',
      'Expanded options chain research & Put/Call ratios',
      '10 Watchlists (up to 150 tickers each)',
      'Up to 50 active technical & webhook alerts',
      '50 Saved research reports',
      '1 Year (365 days) prediction history log',
      'Quantitative backtesting & signal verification',
    ],
    limits: {
      maxAIRequestsPerDay: 100,
      maxMonthlyDeepResearchJobs: 15,
      maxDeepResearchSourcesPerJob: 12,
      maxDeepResearchAiSteps: 10,
      maxDeepResearchTokens: 15000,
      maxSavedResearchReports: 50,
      maxWatchlists: 10,
      maxWatchlistTickers: 150,
      maxAlerts: 50,
      predictionHistoryDays: 365,
      timeframes: ['1m', '2m', '5m', '15m', '30m', '1h', '4h', '1d', '5d', '1w'],
      canUseRealtimeData: true,
      canUseAdvancedAI: true,
      canUseOptions: true,
      canUseAdvancedOptions: false,
      canUseUnusualOptions: false,
      canUseScanner: true,
      scannerLevel: 'advanced',
      canUseBacktesting: true,
      backtestingLevel: 'limited',
      canUseSimilarSignals: true,
      canUsePredictionAccuracy: true,
      canCreateAdvancedAlerts: true,
      canExportReports: true,
      canExportAdvancedData: false,
      canExportPdfResearch: false,
      canUseSecResearch: false,
      canUseEarningsTranscripts: true,
      canUseMacroResearch: true,
      canUseWhatChanged: false,
      hasPriorityResearchQueue: false,
      hasEarlyAccessFeatures: false,
      canAccessApiKeys: true,
      hasPrioritySupport: false,
      canUseConnectedPortfolio: true,
      canUseRiskGuardian: true,
      maxConnectedAccounts: 5,
    },
  },

  premium: {
    id: 'premium',
    name: 'Premium',
    badge: 'BEST FOR DEEP RESEARCH',
    monthlyPrice: 69.99,
    annualMonthlyPrice: 24.92,
    annualBilledTotal: 299.00,
    annualSavingsPercent: 17,
    trialDays: 15,
    description: 'Built for serious investors and research-heavy customers requiring comprehensive institutional intelligence.',
    features: [
      'Everything in Pro',
      'Institutional MarketMind Intelligence Engine',
      'Advanced portfolio risk & concentration analysis',
      'Sector exposure & portfolio beta analysis',
      'Diversification scoring',
      'Full Deep Research suite (40 reports/mo, max 25 sources per job)',
      'Official SEC 10-K / 10-Q filing analysis & footnote reconciliation',
      'Deep earnings intelligence, tone analysis & beat/miss probability',
      'Advanced macro policy models & Fed policy glidepath analytics',
      'Catalyst timeline radar & forward corporate event impact',
      'DCF & peer multiple valuation models with bear/base/bull cases',
      'Portfolio Deep Research & multi-stock comparative research',
      '"What Changed?" delta research tracking material updates',
      'Advanced options intelligence: Unusual Options Flow & Gamma Exposure',
      'Professional PDF research reports export with full citations',
      'Ask MarketMind AI (500 requests/day, high-priority queue)',
      '25 Watchlists (up to 500 tickers each)',
      'Up to 200 active multi-channel alerts (Telegram, Discord, Webhooks)',
      '150 Saved research reports',
      '2 Years (730 days) prediction history log',
      'Priority research queue processing',
    ],
    limits: {
      maxAIRequestsPerDay: 500,
      maxMonthlyDeepResearchJobs: 40,
      maxDeepResearchSourcesPerJob: 25,
      maxDeepResearchAiSteps: 15,
      maxDeepResearchTokens: 35000,
      maxSavedResearchReports: 150,
      maxWatchlists: 25,
      maxWatchlistTickers: 500,
      maxAlerts: 200,
      predictionHistoryDays: 730,
      timeframes: ['1m', '2m', '5m', '15m', '30m', '1h', '4h', '1d', '5d', '1w'],
      canUseRealtimeData: true,
      canUseAdvancedAI: true,
      canUseOptions: true,
      canUseAdvancedOptions: true,
      canUseUnusualOptions: true,
      canUseScanner: true,
      scannerLevel: 'premium',
      canUseBacktesting: true,
      backtestingLevel: 'advanced',
      canUseSimilarSignals: true,
      canUsePredictionAccuracy: true,
      canCreateAdvancedAlerts: true,
      canExportReports: true,
      canExportAdvancedData: true,
      canExportPdfResearch: true,
      canUseSecResearch: true,
      canUseEarningsTranscripts: true,
      canUseMacroResearch: true,
      canUseWhatChanged: true,
      hasPriorityResearchQueue: true,
      hasEarlyAccessFeatures: false,
      canAccessApiKeys: true,
      hasPrioritySupport: true,
      canUseConnectedPortfolio: true,
      canUseRiskGuardian: true,
      maxConnectedAccounts: 20,
    },
  },

  ultra: {
    id: 'ultra',
    name: 'Ultra',
    badge: 'MAXIMUM ACCESS',
    monthlyPrice: 99.99,
    annualMonthlyPrice: 41.58,
    annualBilledTotal: 499.00,
    annualSavingsPercent: 17,
    trialDays: 15,
    description: 'Highest usage allowances, top-tier research capacity, and early access for power investors and wealth managers.',
    features: [
      'Everything in Premium',
      'Maximum MarketMind AI access (2,000 requests/day on priority compute)',
      'Highest available realtime-data priority',
      'Full institutional intelligence suite',
      'Advanced portfolio AI & Advanced options AI',
      'Ultra Deep Research capacity (100 reports/mo, max 50 sources per job)',
      'Deep multi-step reasoning (up to 25 research steps & 80k token synthesis)',
      'Full institutional catalyst & dark pool liquidity radar',
      'Advanced portfolio stress testing & automated Risk Guardian alerts',
      'Full options Greeks surface, volatility smiles & multi-leg payoff simulation',
      'Complete investment memo generation & custom branded PDF exports',
      'Highest saved research capacity (250 saved reports)',
      'Unlimited watchlists subject to abuse controls (up to 2,000 tickers each)',
      'Up to 500 active multi-channel alerts',
      '5 Years (1825 days) prediction history log',
      'Top-priority research queue with instant execution',
      'Direct API keys with maximum throughput limits',
      'Early access to new AI models, experimental features & specialized datafeeds',
      'Dedicated 24/7 technical concierge support',
    ],
    limits: {
      maxAIRequestsPerDay: 2000,
      maxMonthlyDeepResearchJobs: 100,
      maxDeepResearchSourcesPerJob: 50,
      maxDeepResearchAiSteps: 25,
      maxDeepResearchTokens: 80000,
      maxSavedResearchReports: 250,
      maxWatchlists: 50,
      maxWatchlistTickers: 2000,
      maxAlerts: 500,
      predictionHistoryDays: 1825,
      timeframes: ['1m', '2m', '5m', '15m', '30m', '1h', '4h', '1d', '5d', '1w'],
      canUseRealtimeData: true,
      canUseAdvancedAI: true,
      canUseOptions: true,
      canUseAdvancedOptions: true,
      canUseUnusualOptions: true,
      canUseScanner: true,
      scannerLevel: 'ultra',
      canUseBacktesting: true,
      backtestingLevel: 'institutional',
      canUseSimilarSignals: true,
      canUsePredictionAccuracy: true,
      canCreateAdvancedAlerts: true,
      canExportReports: true,
      canExportAdvancedData: true,
      canExportPdfResearch: true,
      canUseSecResearch: true,
      canUseEarningsTranscripts: true,
      canUseMacroResearch: true,
      canUseWhatChanged: true,
      hasPriorityResearchQueue: true,
      hasEarlyAccessFeatures: true,
      canAccessApiKeys: true,
      hasPrioritySupport: true,
      canUseConnectedPortfolio: true,
      canUseRiskGuardian: true,
      maxConnectedAccounts: 50,
    },
  },
};

export const DEFAULT_PLAN: SubscriptionPlanId = 'pro';

/**
 * Normalizes any legacy or alias plan tier to a canonical SubscriptionPlanId.
 */
export function normalizePlanId(rawPlan?: string | null): SubscriptionPlanId {
  if (!rawPlan) return 'free';
  const plan = rawPlan.toLowerCase().trim();
  if (plan === 'ultra' || plan === 'enterprise') return 'ultra';
  if (plan === 'premium' || plan === 'institutional') return 'premium';
  if (plan === 'pro') return 'pro';
  if (plan === 'basic') return 'basic';
  return 'free';
}
