import React, { useState } from 'react';
import {
  HelpCircle,
  BookOpen,
  Search,
  Sparkles,
  ChevronDown,
  ChevronUp,
  LineChart,
  Target,
  Layers,
  ShieldAlert,
  PlayCircle,
  ExternalLink,
  MessageSquare,
} from 'lucide-react';

interface HelpCenterViewProps {
  onOpenContact?: () => void;
  onOpenTour?: () => void;
}

export const HelpCenterView: React.FC<HelpCenterViewProps> = ({
  onOpenContact,
  onOpenTour,
}) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [activeCategory, setActiveCategory] = useState<'all' | 'glossary' | 'indicators' | 'faqs' | 'tutorials'>('all');
  const [expandedFaq, setExpandedFaq] = useState<number | null>(0);

  const GLOSSARY_ITEMS = [
    {
      term: 'VWAP (Volume-Weighted Average Price)',
      category: 'Technicals',
      definition:
        'The true average benchmark price an asset has traded at throughout the day, based on both volume and price. Institutional traders use VWAP as a key liquidity test.',
      example: 'Price trading above VWAP indicates institutional buyers are in control.',
    },
    {
      term: 'Brier Score',
      category: 'Quant Math',
      definition:
        'A strictly proper scoring rule that measures the accuracy of probabilistic forecasts. Scores range from 0.00 (perfect accuracy) to 1.00 (complete inaccuracy).',
      example: 'A forecast of 80% probability that resolves true yields a Brier score of (0.8 - 1.0)² = 0.04.',
    },
    {
      term: 'Gamma Regime & Pinning',
      category: 'Options Flow',
      definition:
        'The measure of how market maker hedging accelerates or dampens price volatility. Positive gamma dampens volatility (mean reversion), while negative gamma amplifies explosive moves.',
      example: 'High open interest at $515 strike creates a magnet pinning effect near expiration.',
    },
    {
      term: 'Put / Call Ratio (PCR)',
      category: 'Sentiment',
      definition:
        'The total volume of traded put options divided by the total volume of call options. PCR < 0.70 is heavily bullish/complacent, while PCR > 1.20 indicates heightened fear/hedging.',
      example: 'A sharp decline in Put/Call ratio during a dip signals aggressive smart-money call buying.',
    },
    {
      term: 'EMA Ribbon (9, 20, 50, 200)',
      category: 'Technicals',
      definition:
        'A sequence of Exponential Moving Averages of varying lengths that illustrates trend strength, direction, and dynamic support/resistance channels.',
      example: 'When 9 EMA > 20 EMA > 50 EMA, the trend exhibits strong bullish momentum alignment.',
    },
    {
      term: 'Relative Volume (RVOL)',
      category: 'Volume',
      definition:
        'Compares current trading volume to the typical average volume for that specific time of day. RVOL > 2.0x indicates significant institutional accumulation or distribution.',
      example: 'A breakout on 2.5x RVOL carries 3x higher statistical follow-through probability.',
    },
  ];

  const FAQS = [
    {
      q: 'How does the Gemini 3.7 Flash AI calculate market bias?',
      a: 'The engine ingests 30+ real-time quantitative inputs—including tick prices, VWAP distance, EMA slopes, sector breadth ratios, and options net delta. It evaluates these inputs against probabilistic regression weights to output a unified directional bias (Bullish, Bearish, or Neutral) and confidence score.',
    },
    {
      q: 'Are the prediction records and win rates verifiable?',
      a: 'Yes. Every signal generated by the terminal is logged immutably with an entry timestamp, target level, stop loss, and Brier score. The resolution engine automatically audits whether target prices were reached during the specified timeframe.',
    },
    {
      q: 'Can I connect MarketMind signals to my Discord or automated trading bot?',
      a: 'Yes! Pro and Institutional members can generate custom Discord Webhooks or REST API keys in Account Settings to forward alerts directly to personal servers, Telegram channels, or algorithmic execution engines.',
    },
    {
      q: 'What is the latency of the Massive WebSocket live feed?',
      a: 'Our direct WebSocket stream connects to low-latency financial edge gateways with typical round-trip tick latency under 25 milliseconds during regular US trading hours (9:30 AM – 4:00 PM ET).',
    },
    {
      q: 'How do I export intelligence briefs as PDF reports?',
      a: 'Navigate to the "Export Reports" tab or click the "Morning Report" button in the terminal header. You can preview, customize individual research sections, and click "Print / Save PDF" or "Export CSV".',
    },
  ];

  const TUTORIALS = [
    {
      title: 'Mastering Intraday VWAP Breakouts',
      duration: '4 mins read',
      tag: 'Strategy Guide',
      summary: 'Learn how to identify false breakouts vs true institutional continuation when price crosses VWAP.',
    },
    {
      title: 'Reading Institutional Options Sweep Flow',
      duration: '6 mins read',
      tag: 'Options Flow',
      summary: 'How to spot smart-money block sweeps on the tape and use Net Delta to anticipate directional expansions.',
    },
    {
      title: 'Configuring Webhook Alerts for High-Probability Pivots',
      duration: '3 mins read',
      tag: 'Automation',
      summary: 'Step-by-step tutorial on forwarding real-time RSI and Support/Resistance alerts to Discord.',
    },
  ];

  const filteredGlossary = GLOSSARY_ITEMS.filter(
    (g) =>
      g.term.toLowerCase().includes(searchQuery.toLowerCase()) ||
      g.definition.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="flex flex-col gap-3 select-none text-[#e2e8f0]">
      {/* Header Bar */}
      <div className="bg-[#15171a] border border-[#2d3139] rounded-lg p-4 flex flex-wrap justify-between items-center gap-3">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-[#6366f1]/20 border border-[#6366f1]/40 flex items-center justify-center text-[#818cf8]">
            <HelpCircle className="w-4 h-4" />
          </div>
          <div>
            <h2 className="text-sm font-black text-white uppercase tracking-wider flex items-center gap-2">
              <span>Help Center &amp; Quant Knowledge Base</span>
              <span className="text-[10px] px-1.5 py-0.2 bg-[#6366f1]/20 text-[#a5b4fc] border border-[#6366f1]/40 rounded font-mono">
                ACADEMY &bull; GLOSSARY
              </span>
            </h2>
            <p className="text-xs text-slate-400">
              Master technical indicators, quantitative mathematics, options flow &amp; terminal shortcuts
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {onOpenTour && (
            <button
              onClick={onOpenTour}
              className="px-3 py-1.5 bg-[#252830] hover:bg-[#2e323d] text-slate-200 text-xs font-bold rounded-lg border border-[#2d3139] flex items-center gap-1.5 transition"
            >
              <PlayCircle className="w-3.5 h-3.5 text-[#818cf8]" />
              <span>Launch Onboarding Tour</span>
            </button>
          )}

          {onOpenContact && (
            <button
              onClick={onOpenContact}
              className="px-3 py-1.5 bg-[#6366f1] hover:bg-[#4f46e5] text-white text-xs font-bold rounded-lg flex items-center gap-1.5 transition shadow-sm"
            >
              <MessageSquare className="w-3.5 h-3.5" />
              <span>Contact Support</span>
            </button>
          )}
        </div>
      </div>

      {/* Search & Category Filter */}
      <div className="bg-[#181a1f] border border-[#2d3139] rounded-xl p-3 flex flex-wrap justify-between items-center gap-3">
        <div className="relative flex-1 max-w-md">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search indicator, glossary term, or question..."
            className="w-full bg-[#14161a] border border-[#2d3139] focus:border-[#6366f1] text-xs text-white pl-9 pr-3 py-2 rounded-lg focus:outline-none"
          />
        </div>

        <div className="flex items-center gap-1 bg-[#14161a] p-1 rounded-lg border border-[#2d3139] text-xs font-bold">
          {(['all', 'glossary', 'faqs', 'tutorials'] as const).map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={`px-3 py-1 rounded transition uppercase text-[11px] ${
                activeCategory === cat
                  ? 'bg-[#6366f1] text-white'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {/* Main Grid Content */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-3">
        {/* Left Column: Quant Glossary (7 cols) */}
        {(activeCategory === 'all' || activeCategory === 'glossary') && (
          <div className="md:col-span-7 bg-[#181a1f] border border-[#2d3139] rounded-xl p-4 space-y-3">
            <div className="flex items-center justify-between border-b border-[#2d3139] pb-2">
              <div className="flex items-center gap-1.5">
                <BookOpen className="w-4 h-4 text-[#818cf8]" />
                <h3 className="text-xs font-bold text-white uppercase tracking-wider">
                  Quantitative Trading Glossary
                </h3>
              </div>
              <span className="text-[10px] text-slate-400 font-mono">
                {filteredGlossary.length} terms
              </span>
            </div>

            <div className="space-y-3">
              {filteredGlossary.map((item, idx) => (
                <div
                  key={idx}
                  className="p-3 bg-[#14161a] rounded-lg border border-[#2d3139] hover:border-slate-600 transition space-y-1.5"
                >
                  <div className="flex justify-between items-start">
                    <h4 className="text-xs font-bold text-white">{item.term}</h4>
                    <span className="text-[9px] px-1.5 py-0.2 bg-[#6366f1]/20 text-[#a5b4fc] border border-[#6366f1]/40 rounded font-mono">
                      {item.category}
                    </span>
                  </div>
                  <p className="text-[11px] text-slate-300 leading-relaxed">
                    {item.definition}
                  </p>
                  <div className="text-[10.5px] text-emerald-400/90 font-mono bg-emerald-950/20 p-1.5 rounded border border-emerald-500/20">
                    <span className="font-bold">Trading Application: </span>
                    {item.example}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Right Column: FAQs & Strategy Guides (5 cols) */}
        <div className={`${activeCategory === 'glossary' ? 'hidden' : activeCategory === 'faqs' || activeCategory === 'tutorials' ? 'md:col-span-12' : 'md:col-span-5'} space-y-3`}>
          {/* Strategy Tutorials */}
          {(activeCategory === 'all' || activeCategory === 'tutorials') && (
            <div className="bg-[#181a1f] border border-[#2d3139] rounded-xl p-4 space-y-3">
              <div className="flex items-center gap-1.5 border-b border-[#2d3139] pb-2">
                <Sparkles className="w-4 h-4 text-amber-400" />
                <h3 className="text-xs font-bold text-white uppercase tracking-wider">
                  Quant Trading Guides
                </h3>
              </div>

              <div className="space-y-2">
                {TUTORIALS.map((tut, i) => (
                  <div
                    key={i}
                    className="p-2.5 bg-[#14161a] rounded-lg border border-[#2d3139] hover:border-[#6366f1]/50 transition space-y-1"
                  >
                    <div className="flex justify-between items-center">
                      <span className="text-[9px] font-mono text-emerald-400 font-bold uppercase">
                        {tut.tag}
                      </span>
                      <span className="text-[9px] text-slate-500 font-mono">{tut.duration}</span>
                    </div>
                    <h4 className="text-xs font-bold text-white">{tut.title}</h4>
                    <p className="text-[11px] text-slate-400 leading-relaxed">{tut.summary}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* FAQs Accordion */}
          {(activeCategory === 'all' || activeCategory === 'faqs') && (
            <div className="bg-[#181a1f] border border-[#2d3139] rounded-xl p-4 space-y-3">
              <div className="flex items-center gap-1.5 border-b border-[#2d3139] pb-2">
                <HelpCircle className="w-4 h-4 text-[#818cf8]" />
                <h3 className="text-xs font-bold text-white uppercase tracking-wider">
                  Frequently Asked Questions
                </h3>
              </div>

              <div className="space-y-2">
                {FAQS.map((faq, index) => {
                  const isOpen = expandedFaq === index;
                  return (
                    <div
                      key={index}
                      className="border border-[#2d3139] bg-[#14161a] rounded-lg overflow-hidden transition"
                    >
                      <button
                        onClick={() => setExpandedFaq(isOpen ? null : index)}
                        className="w-full text-left p-2.5 flex justify-between items-center text-xs font-bold text-white hover:bg-[#1c1f24] transition"
                      >
                        <span className="pr-2">{faq.q}</span>
                        {isOpen ? (
                          <ChevronUp className="w-3.5 h-3.5 text-slate-400 shrink-0" />
                        ) : (
                          <ChevronDown className="w-3.5 h-3.5 text-slate-400 shrink-0" />
                        )}
                      </button>
                      {isOpen && (
                        <div className="p-2.5 pt-0 text-[11px] text-slate-300 leading-relaxed border-t border-[#23272f]">
                          {faq.a}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
